### ISSUE TITLE
Reset the view name after loading the background file

### ISSUE THREAD

**Issue by Limraj** [SCADA-LTS/Scada-LTS#1075]
## Expected Behavior
After loading the background file, the name should not be reset.

## Actual Behavior
After loading the background file, the view name resets.

## Steps to Reproduce the Problem
1. Open Graphical Views;
2. Click New View;
3. Set name for view;
4. Choose Background image;
5. Click Upload image;

## Specifications
- Version: SCADA-LTS v2.0.0
- Platform: Windows 7 - 64-bit
- Subsystem: Old UI ScadaBR

**Comment by nduvernois** [comment]
still present in release 2.6.18
