### ISSUE TITLE
Docker on Windows. The start command gives an error.

### ISSUE THREAD

**Issue by espirit** [SCADA-LTS/Scada-LTS#1085]
I am running docker on Windows. The start command gives an error.

When I change the -e DOCKER_HOST_IP='docker-machine ip' to -e DOCKER_HOST_IP="docker-machine ip", the image starts.

using http://localhost:81 I get the Tomcat page.
using http://localhost:81/ScadaLTS/ gives a page-not-found

**How do I get ScadaLTS in my browser**?

I also ran the image 'scadalts/scadalts:new_develop'. That runs using http://localhost:81/ScadaLTS/, but I have not login data (name/password).

**Please help me to get started on this**.

**Comment by Limraj** [comment]
Hi @espirit,
The correct address is: ('-' character was missing)
http://localhost:81/Scada-LTS/

Regards,
Kamil Jarmusik
