### ISSUE TITLE
Publisher/HTTP Sender save button generate SQLexception with MariaDB10.4 and Windows10 

### ISSUE THREAD

**Issue by WagnerDeQueiroz** [SCADA-LTS/Scada-LTS#1146]
When creating a new Publisher **HTTP Sender**  on a fresh new ScadaLTS we got a SQLException saving any example:

_The error is:_ 

PreparedStatementCallback; uncategorized SQLException for SQL []; SQL state [null]; error code [0]; Can only convert a byte[] to BINARY, VARBINARY or LONGVARBINARY;
nested exception is 
**java.sql.SQLException**: Can only convert a byte[] to BINARY, VARBINARY or LONGVARBINARY

Found with Tomcat7 / Windows 10 / MariaDB 10.4
Using derby on same instalation, this error not appear...

![image](https://user-images.githubusercontent.com/7959613/76682002-fbcacc80-65d6-11ea-8ae3-1743a7561fa6.png)

**Comment by grzesiekb** [comment]
Is the same situation with the docker? 
Docker can also be installed on windows.

**Comment by WagnerDeQueiroz** [comment]
I don't have experience with docker. Its possible known what version of each program is used on to install the ScadaLTS on Windows?

**Comment by grzesiekb** [comment]
Thank you for your test, if you could write to me on facebook, I will give you contact to the decision maker in matters of work on ScadaLTS.  https://www.facebook.com/ScadaLTS

**Comment by Brent-Frere** [comment]
We'll try to reproduce this issue on Thursday.

**Comment by Brent-Frere** [comment]
Sorry, I didn't had time for this. I'll try to reproduce this issue during the week-end or on Monday, despite I'm very busy...

**Comment by Limraj** [comment]
Hi @WagnerDeQueiroz,
I can't reproduce this bug on 2.7.5.3, it probably doesn't exist anymore.

When it comes to installing the source for windows, we have prepared a complete installer, it also installs the mysql database:
https://github.com/SCADA-LTS/windows-installer

If the problem persists, you can reopen this issue.

Regards,
Kamil Jarmusik
