### ISSUE TITLE
PointLink

### ISSUE THREAD

**Issue by mateuszhyski** [SCADA-LTS/Scada-LTS#1151]
## Expected Behavior

Point Link works

## Actual Behavior

Point Link work but only once. That means that value is change only once.

That branche will have only solution which exist also in #961. I create this branche because, during try to merge #961 to siv/develop, #961 contained a lot of not mine files.

## Steps to Reproduce the Problem

1. We have Virtual Data Source and two points under VDS which one from them have his property as settable.
2. Create Point Link and set source point as point which do not have settable property. Set target as point which have property as settable. 
3.As Script inside PointLink , we have:
If (source.value == '1') {
{
return 'A';
}
else
{
return 'B';
}
That script is as example only which depends on source value, change target value.
4. Save PointLink
5.Value of target point are is change depends on source on watch list. 

## Specifications

    Version: v2.2.0
    Platform: Linux
    Subsystem: open jdk 1.8, mysql 5.7, nodejs 8.12.0

**Comment by grzesiekb** [comment]
#1154
