### ISSUE TITLE
Scroll bar on main page 

### ISSUE THREAD

**Issue by jeffersonpimenta** [SCADA-LTS/Scada-LTS#1222]
Hi,

I have an application to watch solar inverters on ScadaLTS and i'm almost running out of space on Points area:

![image](https://user-images.githubusercontent.com/11169349/81823008-346d2080-950a-11ea-830b-6d99dee48e8c.png)

In the next versions its possible to implement a scroll bar on it? I know that its possible to adjust the size of it or use zoom out to see hidden points, but it will be nice to have a scroll bar on it!

Thank you very much!

Edited:

I just notice that in modern watch list Scada have a scroll bar, but it miss the adjust button on height charts:

![image](https://user-images.githubusercontent.com/11169349/81825212-be1ded80-950c-11ea-8dad-6093b42f3343.png)

**Comment by grzesiekb** [comment]
if you change height You need to refresh window (Ctrl + R) to see the scroll in the tree with list points.

![81823008-346d2080-950a-11ea-830b-6d99dee48e8c](https://user-images.githubusercontent.com/1280575/81831420-9c892a00-953d-11ea-90fa-ffb635cde1f7.png)

**Comment by jeffersonpimenta** [comment]
Everything works fine with F5! Thanks!
