### ISSUE TITLE
Error on database ScadaLTS 2.2.1  Rpi3b+ 

### ISSUE THREAD

**Issue by jeffersonpimenta** [SCADA-LTS/Scada-LTS#1237]
Hi, after trying install ScadaLTS on Rpi3b+  i got the error on catalina.out:

SEVERE: Unable to create initial connections of pool.

After that i tough that i was running on bad mysql configuration, but after open mysql and check if scadalts has created the tables on database i saw that the system create all tables without problems.

![image](https://user-images.githubusercontent.com/11169349/82510649-7fc29880-9ae1-11ea-9948-af2f6463123a.png)

My java version is openjdk version "1.8.0_212" and tomcat7.

Previous i had a mysql error that i manage to solve copying lib files under web-inf/lib to tomcat7/lib. But this time i had to download mysql-connector version 5.1.27, 5.1.38, 5.1.46 and 8.0.20 in order to overcome the error of missing connector

My context.xml is exacly like the example [here](https://github.com/SCADA-LTS/Scada-LTS/wiki/Install-Scada-LTS-on-linux) with my credentials.

My env.properties is like
![image](https://user-images.githubusercontent.com/11169349/82511146-e5fbeb00-9ae2-11ea-971d-9190c3759c80.png)
![image](https://user-images.githubusercontent.com/11169349/82511156-ebf1cc00-9ae2-11ea-8e66-32100da0a25f.png)

My env.properties.mysql is like
![image](https://user-images.githubusercontent.com/11169349/82511120-d4b2de80-9ae2-11ea-89cc-ffa9639b030b.png)

When i try to access the webpage i got:
![image](https://user-images.githubusercontent.com/11169349/82511313-57d43480-9ae3-11ea-88cc-c17eec7c840a.png)

![image](https://user-images.githubusercontent.com/11169349/82511328-5f93d900-9ae3-11ea-8632-4515b035bb06.png)

![image](https://user-images.githubusercontent.com/11169349/82511342-66225080-9ae3-11ea-9e3a-aae19df9b1cb.png)

IKD if my question was a lame question, but i got success so far last time i try to put this setup on my rpi and got this error on newer version of scadalts.

Thanks everyone!

**Comment by grzesiekb** [comment]
In **env.properties** if configure connection in context.xml
```
db.type=mysql
db.datasource=true
db.datasourceName=java:comp/env/jdbc/scadalts

```

And you need to copy the appropriate libraries to the database connections as well as to tomcat.

**Comment by jeffersonpimenta** [comment]
I first try using both env.properties and env.properties.mysql. No success. same error.

Then i rename those files to .old and create a new env.properties with only three lines you have mentioned. Same error.

I try to unistall every other java version but 7 and set it on tomcat7. Same error.

[catalina.zip](https://github.com/SCADA-LTS/Scada-LTS/files/4668796/catalina.zip)

TY for your help! :D

**Comment by grzesiekb** [comment]
I would need access through Ana Desk, for example. To check it out.

**Comment by jeffersonpimenta** [comment]
I could give you access to my computer via teamview. Contact me via jefferson.pimenta@hotmail.com or engjeffersonpimenta@gmail.com

I have both rpi working and not
 
TY!
