### ISSUE TITLE
Duplicated EventHandlers in PointEventHandlers list

### ISSUE THREAD

**Issue by radek2s** [SCADA-LTS/Scada-LTS#1465]
## Expected Behavior
When user create a new Event Handler for specific Point Event Detector it should be bonded with only one PED. 

## Actual Behavior
Inside Database There is a relation between EH and only one PED but on the _/ScadaBR/event_handlers.shtm_ there are duplicated Event Handlers for each Point Event Detector related to specific DataPoint.
 
## Steps to Reproduce the Problem

1. Create 2 or more Point Event Detectors for specific Datapoint in _ScadaBR/data_point_edit.shtm_.
2. Create 1 Event Handler for specific PED on the _/ScadaBR/event_handlers.shtm_ page.
3. Refresh this page and check other PEDs for that specific Datapoint. 

## Screenshoots

![image](https://user-images.githubusercontent.com/22638815/102075956-4cda4c00-3e07-11eb-84d2-ab32a463933f.png)

**Comment by Limraj** [comment]
https://github.com/SCADA-LTS/Scada-LTS/issues/2063
