### ISSUE TITLE
Building on travis using gradle

### ISSUE THREAD

**Issue by grzesiekb** [SCADA-LTS/Scada-LTS#1501]
### Expected Behavior
building on travis using gradle

### Actual Behavior
building on travis using ant

### Specifications

Version: scada 2.6
Platform: Ubuntu 16.04, 
Subsystem: node 12.09, mysql 5.7, jdk 11

**Comment by radek2s** [comment]
Travis.org has been disabled in our project and we moved to GitHub Actions that build our project using Gradle
#1849
