### ISSUE TITLE
Updating Alarms table on the new UI

### ISSUE THREAD

**Issue by arturro96** [SCADA-LTS/Scada-LTS#1545]
### Expected Behavior
Alarms table will contain additional columns:
- Description (Point description field from Point Properties)
- Event Message (Event text renderer associated to the point in current state which is defined in Point Properties)

Table appearance task:
- Decreasing the space between rows in table, so in graphical view table could contain more events

Additional feature to the table:
- Filtering

### Actual Behavior

![Zrzut ekranu 2021-02-24 o 12 17 25](https://user-images.githubusercontent.com/29277522/108993059-54855f00-769a-11eb-8954-9de964de09fa.png)

## subtasks

[x] #1556 
[x] #1558 
[x] #1560 
[x] #1565

### Specifications
Version: 2.6.0
Platform: Linux

**Comment by grzesiekb** [comment]
hWhere should I add a description of what it should be called, what API to use?
