### ISSUE TITLE
Alarm Notification Flag that use WebSockets

### ISSUE THREAD

**Issue by radek2s** [SCADA-LTS/Scada-LTS#1623]
**Expected Behavior**
Notification Flag in main Scada-LTS header informs users about the highest alarm level in System using classic doLongPool mechanism. During the migration to the new User Interface we try to use WebSocket mechanism to handle the highest alarm level.
**Actual Behavior**
Mechanism based on the DWR methods.

*Specifications*
Version: 2.7.0
Platform: Linux

**Comment by Limraj** [comment]
#1921
