### ISSUE TITLE
readme document docker startup url wrong

### ISSUE THREAD

**Issue by huanghe-1** [SCADA-LTS/Scada-LTS#1684]
the lastest docker image, startup url is  ScadaBR not ScadaLTS，change  the readme document or the docker.

Type in docker IP adrress in the browser with port 81 and /ScadaBR / sufix. Example: 
http://10.0.75.2:81/ScadaBR /

and,how to pull a requests,tip  no permission

**Comment by radek2s** [comment]
Hello @huanghe-1! 
Check our [Wiki page](https://github.com/SCADA-LTS/Scada-LTS/wiki/Run-ScadaLTS-on-docker---instruction) with tutorial how to use docker with our Scada-LTS

**Comment by huanghe-1** [comment]
Wiki page is right, readme  mistake

**Comment by radek2s** [comment]
Readme will be soon refactored, but we try migrate to Wiki page that is much easier to maintain. Readme file will be redirecting to specific sections on our Wiki and there you will be able to find the latest updates.
