### ISSUE TITLE
Désactivation des points de données lors du redémarrage de tomcat

### ISSUE THREAD

**Issue by gueyefat** [SCADA-LTS/Scada-LTS#1712]
Bonjour,
J'ai installé ScadaLTS 2.5.1 sur mon serveur et lorsque je redémarre tomcat, tous mes points de données se retrouve être désactivés.
Sauriez-vous d'où vient le soucis. 
Merci de votre aide.

**Comment by Limraj** [comment]
Hi @gueyefat,
Check with the latest version 2.7.5.3 if this issue occurs. If it still occurs, more detailed information about the configuration is needed, e.g. providing a configuration export in the form of a json file.

Function is in Export/Import -> Export Project:
![Screenshot 2023-06-03 at 12 51 40](https://github.com/SCADA-LTS/Scada-LTS/assets/35842300/ee7781cd-36b7-4e9a-bcef-c92ff1f37a77)

Export/Import -> check export object -> click on 'Generate JSON':
![Screenshot 2023-06-03 at 12 52 06](https://github.com/SCADA-LTS/Scada-LTS/assets/35842300/df135c92-0ec1-4d6f-936f-159d19a0bb98)

Regards,
Kamil Jarmusik
