### ISSUE TITLE
Addition of new column in points on context table in scripts

### ISSUE THREAD

**Issue by arturro96** [SCADA-LTS/Scada-LTS#1733]
*Expected Behavior*
Points on context table has additional column with point XID.

*Actual Behavior*
When datapoints are added to script context, in "Var" field the following naming convention is used: p + dataPointId (taken from database). When dataPointId changes somehow, var names aren't updated and we lose information which point we have in script.

*Specifications*

Version: 2.7.1
Platform: macOS

**Linked:**
#2762

**Comment by fabiodurao** [comment]
It's interesting to unify everything around XID. Today the database table that shows the datapoint values, loads the datapointID and not the XID, so to make external integrations with systems like Grafana, we use Select in the table referring to the datapointID, it would be better if it was the XID. Another place that this happens is in server side scripts, when we want to create something that brings the values of several datapoints, the reference again is by the datapointID, which is kind of hidden from the user, you can only find this value by the url when looking at the datapoint details or adding in context, as mentioned above.
