### ISSUE TITLE
Improve AmChart performance and User Experience

### ISSUE THREAD

**Issue by radek2s** [SCADA-LTS/Scada-LTS#1761]
**Expected Behavior**
- Display last Data Point value (even if in specific period of time there was no update)
- Display notification that will inform user that specific data point does not contain any values.
- Inform about "not reliable data" instead of display nothing.

**Actual Behavior**
Charts are loading very long for huge amount of data. Additionally if there are any data in specific DataPoint there is no message about that and user may think that something does not work.

*Specifications*
Version: 2.6.7
Platform: Linux

**Comment by fabiodurao** [comment]
This is very interesting, today when we want a chart that shows data from datapoints that don't change much, with binary and numeric setpoints, we choose the option to register "all data". This causes storage to increase unnecessarily.

Last time I talked about this with the developers, I was told that the intention was not to show data that was not actually read, giving false impression of update, but this solution proposed above seems to solve all related issues.

**Comment by radek2s** [comment]
Hope that this commits will also reduce the CPU and memory usage issue #1478 reported by @OlleRatu.
Resolve #1478
