### ISSUE TITLE
Problem with the script button styles

### ISSUE THREAD

**Issue by grzesiekb** [SCADA-LTS/Scada-LTS#1844]
**Problem with the script button styles**
in the new version, ScadaLTS
 styles for script buttons are displayed as for labels
is 
![Screenshot_2021-08-10_10-27-36](https://user-images.githubusercontent.com/1280575/128835575-2adc8037-4665-475a-b340-d4266d37d07e.png)

and it should be
![Screenshot_2021-08-10_10-29-06](https://user-images.githubusercontent.com/1280575/128835633-8810c983-4031-4d65-83e4-7b986bede678.png)

**To Reproduce**
1.Create view
2. Add script button
3. we see the button as a label 

**Expected behavior**

We expect the script button to be displayed as a button
![Screenshot_2021-08-10_10-29-06](https://user-images.githubusercontent.com/1280575/128835650-075a22a2-aeb9-4c5e-8082-5fa87eb22401.png)

**Comment by sselvaggi** [comment]
I fixed it for each theme
