### ISSUE TITLE
Graphical views Scada-LTS

### ISSUE THREAD

**Issue by jmuguruza** [SCADA-LTS/Scada-LTS#1961]
I am running OpenPLC (port 8081) and ScadaLTS (port 8080 with mysql database) using Docker Compose. 
I loaded an example program on the PLC, taken from GitHub, named waterheater.st and then ran the PLC. 
So, now I make the connection with Scada-LTS using Modbus IP on port 502, after including the background image of the waterheater program and the .json file at the import/export.
Then I go to graphical views and try to interact with some buttons that I create, but I got an error from localhost:8080 saying:
Incorrect result size: expected 1, actual 0

Can someone find a solution for this? 
Thanks in advance

**Comment by Limraj** [comment]
Hello @jmuguruza, 
some questions:
1. When you edit data source Modbus IP, do you have any errors in:
![modbus_error](https://user-images.githubusercontent.com/35842300/143445936-31468fbe-ed63-4eb4-9c33-6134672e814e.png)
Perhaps you could make a screenshot?
2. Can we get the json file you are trying to import? (kamil.jarmusik@softq.pl) 
3. You import via the function Import / Export-> paste json into the "data" text field and click the "Import" button? (marked in red in the screen) ![exporst](https://user-images.githubusercontent.com/35842300/143445115-8aae53f5-5751-4a1e-9209-58e780226d8c.png)
4. Maybe you would be able to make a screenshot when this error occurs?

Regards

**Comment by jmuguruza** [comment]
1- I do not get any errors
3- I copy the whole file and paste it into the "data" field and click "Import" right, and I get the same errors. 
![import_export](https://user-images.githubusercontent.com/78322990/143843811-22470b97-7db9-4e15-a692-8e5a3919513a.JPG)
4- I get an error like the one of the image below
![Error](https://user-images.githubusercontent.com/78322990/143843940-ec512fe7-4f62-4950-b4c7-473d73d8f84f.JPG)
