### ISSUE TITLE
it is not possible to set the background resolution

### ISSUE THREAD

**Issue by grzesiekb** [SCADA-LTS/Scada-LTS#2015]
**it is not possible to set the background resolution**

For existing views, something has gone wrong and the property to set the background resolution is not displayed.

**To Reproduce**
1. Go to existing graphical view
2. Click on edit
3. See (don't see)  resolution is not displayed
![Screenshot_2021-12-27_23-57-12](https://user-images.githubusercontent.com/1280575/147515013-3bbeb344-8a62-4fd1-be9f-b3da41c4e41f.png)

**Comment by Limraj** [comment]
Hey i failed to repeat this problem what did i do?
1) I created a new view with no background, it was possible to choose the resolution, then I saved and reloaded the page, I chose the added view and that resolution is still there;
2) Then I added background to this view, uploaded, saved, resolution disappears, but after clicking clear image, the resolution reappears, and it is also after refreshing the page and selecting and editing this view again;

So I conclude that the background is set on that existing view, but maybe the graphics are not available.
