### ISSUE TITLE
Data problem in the new watch list

### ISSUE THREAD

**Issue by grzesiekb** [SCADA-LTS/Scada-LTS#2016]
**Data problem in the new watch list**

**To Reproduce**
1. Define two points virtual data source numeric change 5 second - type Inccrement  
  - Maximum 100, change 30, start value 9
  - Maximum 1000, change 300, start value 0
2. Click on new modern watch list (new ui)
3. Create new watch list
4. Add two points.
5. Remove one
6. Add second point
7. We don't see second poinst on chart howover is defined.

![Screenshot_2021-12-28_07-09-41](https://user-images.githubusercontent.com/1280575/147534040-97f71f62-0642-488d-a6df-66f80fc1f26f.png)

![Screenshot_2021-12-28_07-09-58](https://user-images.githubusercontent.com/1280575/147534050-3c250288-72dd-4a89-9684-fd4dc0bc2751.png)

**Comment by ga7x** [comment]
I tested the new modern watch list. I added two points. Then I deleted one. Then I added the second one. All points are shown. We see second point on chart however is defined.
