### ISSUE TITLE
Fixed 'View charts' for report with events

### ISSUE THREAD

**Issue by Limraj** [SCADA-LTS/Scada-LTS#2019]
**Description**
For a report with events, an attempt to generate charts ends with an exception "System Exception". With the same exception, the call to the function 'Export events' ends.

**To Reproduce**
1. Create datasource ds_1 (virtual, enable), datapoint dp_1 (settable, numeric, no change), eventdetector ed_1 (change, information);
2. Go to 'Watchlists' and change value for dp_1, this should generate an event with the information level;
3. Go to 'Reports';
4. Click on 'New report';
5. Set rep_1 in 'Report name';
6. Add point ds_1 - dp_1 in 'Points';
7. Select 'All events' in 'Events'
8. Check 'Relative to report time'-> 'Past';
9. Click save;
10. Click 'Run now', and reload page;
11. Report rep_1 should appear in 'Report queue' table;
12. Click on 'View charts' for report rep_1 -> System Exception;
13. Click on 'Export events' for report rep_1 -> System Exception;

**Specification:**
 - Scada version: 2.6.10

**Comment by Golffies** [comment]
The "system exception" error was not reproducible, neither on version 2.6.1 (scadadev), nor on version 2.6.10-rc1 (scadatest).

In both cases, it is possible to display the charts or export the data without triggering the error.

In attachment, the display of the charts resulting from the test on 2.6.10-rc1 on the left and on 2.6.1 on the right, without error.

![Capture d’écran 2022-01-20 à 12 22 55](https://user-images.githubusercontent.com/5718159/150333022-25ed6efe-5347-4620-bd4f-76bddb68749b.png)
.

**Comment by Golffies** [comment]
The "system exception" error was reproducible on version 2.6.1 (scadadev - on the right), provided that the new report is applied to a data point with a "high limit" type event detector. Under that same condition, the same error was not reproducible on version 2.6.10-rc1 (scadatest - on the left).

![Capture d’écran 2022-01-20 à 16 21 46](https://user-images.githubusercontent.com/5718159/150359444-29d412c2-742d-4146-ad6a-f510977697cb.png)
