### ISSUE TITLE
simplePoint changevalue popup has no background

### ISSUE THREAD

**Issue by hjbleier** [SCADA-LTS/Scada-LTS#2042]
**Problem**
There is no background on the value change popup window.
It appears to be a problem with the CSS for the modern theme.

**To Reproduce**
Scada-LTS 2.6.10-rc1
Modern Theme selected for the user
drop a simplePoint on a new view display
check box to enable controls
then save the view
open up the new view page
try clicking on the value to change.

**Expected behavior**
There should be a white background or other color so the user
doesn't get confused when text overlaps.

**Environment**
 - OS: Linux
 - Browser: chrome, firefox
 - Version: Scada-LTS 2.6.10-rc
 
![simplePoint--no-background](https://user-images.githubusercontent.com/32180458/149865259-f56d49d0-9484-4416-bc0a-cc98ed02395d.png)
1

**Comment by Limraj** [comment]
#2042

**Comment by hjbleier** [comment]
@radek2s Thank you. I manually added your changes to my current deployment of 2.6.10-rc1 and it fixed the problem, just had to clear the web browsers cache on all the machines that previously logged in. Thanks!
