### ISSUE TITLE
how about this project commercial models? how to continue heathly

### ISSUE THREAD

**Issue by huanghe-1** [SCADA-LTS/Scada-LTS#2044]
After all，engineer need food,company need to survive

**Comment by Limraj** [comment]
Hey @huanghe-1 , if you have any suggestion, please contact: 
michal.rokitianski@softq.pl
kamil.jarmusik@softq.pl

Greetings,
Kamil Jarmusik

**Comment by huanghe-1** [comment]
do your company have some Careers？i'm pleasure to join

**Comment by Limraj** [comment]
Hi @huanghe-1,
If you still think about some kind of cooperation, e.g. you have some clients who need Scada, write to Fryderyk.
If you would like to get involved as a programmer/engineer, we encourage you to get involved in the project(e.g. proposing changes, corrections, testing our protocols, etc.), we'll see what we come up with.

Regards,
Kamil Jarmusik
