### ISSUE TITLE
User not authorized error in new UI

### ISSUE THREAD

**Issue by radek2s** [SCADA-LTS/Scada-LTS#2047]
**Describe the bug**
When we log in as a non-admin user to the new UI after the providing a new notification component we can notice that there is an "user is not authorized" message. That is caused by two API methods that are invoked when user is moving to the WatchListVue page and the new UI. 

**To Reproduce**
1. Reproduce first problem:
1.1 Login as non-admin;
1.2. Go to 'Modern Watch List Vue'
1.3. See error
![MicrosoftTeams-image](https://user-images.githubusercontent.com/22638815/150137194-b43a9d70-4bd0-431f-90d7-e323b878ffa7.png)

2. Reproduce second problem:
2.1. Login as non-admin;
2.2. Go to 'Modern Watch List Vue';
2.3. Sometimes, at this point, the user icon is not visible, only refreshing the page causes the icon to appear;
![Screenshot 2022-01-19 at 14 50 48](https://user-images.githubusercontent.com/35842300/150143703-1ae41b11-5149-426c-aa47-e1cea26de45c.png)

3. Reproduce third problem:
3.1. Login as non-admin;
3.2. Go to 'Modern Watch List Vue';
3.3. I click the button in the upper right corner with the icon symbolizing the user;
3.4. I click on "Edit profile" and nothing appears, only after refreshing the page, the editing form appears, in console log visible error: "Cannot read properties of undefined (reading 'image')";
![Screenshot 2022-01-19 at 14 41 56](https://user-images.githubusercontent.com/35842300/150142205-9acdd274-efb8-4b86-9b86-8540e38308d4.png)

**Expected behavior**
Fix the getAll method to return the all accessible DataPoints for this user from database. If there is none datapoints return an emtpy array.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Chrome

#2090

**Comment by Limraj** [comment]
Merged #2090 (to version 2.7.1)
