### ISSUE TITLE
No data updates in watch list and graphical views.

### ISSUE THREAD

**Issue by grzesiekb** [SCADA-LTS/Scada-LTS#2081]
**No data updates in watch list and graphical views.**
I don't see changes in the graphical view

**To Reproduce**
1. Create database scadalts
2. Start SCADA version 2.6.10
3. Load configuration from project in attachment. 
[Scada-LTS-2.5(2).zip](https://github.com/SCADA-LTS/Scada-LTS/files/8032163/Scada-LTS-2.5.2.zip)

4. Stop SCADA version 2.6.10
5. Replace version scada to newest 2.6.12
6. Start SCADA version 2.6.12
7. On the watch-list we don't see change for point test_events - plc_is_not_available.

**Expected behavior**
On the watch list, we should know the point change  test_events - plc_is_not_available every five seconds

#2086

**Comment by Limraj** [comment]
Hey, this bug has been fixed with a topic: #2086.
I think you can close.
