### ISSUE TITLE
In Data Sources page MetaDataSource description is not escaped

### ISSUE THREAD

**Issue by radek2s** [SCADA-LTS/Scada-LTS#2092]
**Describe the bug**
When user open the Data Sources page if the point of MetaDataSource type has an "script" tag it can be executed on page load.

**To Reproduce**
1. Create Point of MetaDataSource with following return value: `return <script>alert('Hi!')</script>`
2. Move to DataSources page.
3. See an Alert with "Hi" message.

**Expected behavior**
Description field in Data Sources page should escape the `script` tag and the content should not be executed there.

**Screenshots**
![SXSS1](https://user-images.githubusercontent.com/22638815/154241115-8f2114aa-b302-42b3-a51a-1780609a2778.png)
![SXSS2](https://user-images.githubusercontent.com/22638815/154241120-f899dc8a-efc2-48c5-9f7d-38bddfa81427.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Chrome

**Comment by AdisonCavani** [comment]
Fixed in #2103
