### ISSUE TITLE
Doubled database entries

### ISSUE THREAD

**Issue by grzesiekb** [SCADA-LTS/Scada-LTS#2104]
**Describe the bug**
duplicate database entries with the same values for time and value

**To Reproduce**
[Go to '...'](https://web.testquality.com/site/scada-lts/project/1077/tests?folderId=369264&testId=327580)

**Expected behavior**
no duplicate entries in the database with the same time and value

**Screenshots**

![Screenshot_2022-02-21_13-08-41](https://user-images.githubusercontent.com/1280575/154954230-a3d40be4-2abf-4f78-a9cb-1405e20b1908.png)

**Comment by Limraj** [comment]
Config for test:
[Scada-LTS-2.5_2069.zip](https://github.com/SCADA-LTS/Scada-LTS/files/8014358/Scada-LTS-2.5_2069.zip)

SQL for test:

`select pva.pointValueId, pva.textPointValueShort, pva.textPointValueLong, pva.sourceType, pva.sourceId, FROM_UNIXTIME(pv.ts/1000.0) from pointValueAnnotations pva left join pointValues pv on pva.pointValueId = pv.id where pva.pointValueId in (select pv1.id from pointValues pv1 where pv1.dataPointId = META_DATAPOINT_ID) order by pva.pointValueId desc limit 1000;`
