### ISSUE TITLE
Correct report test email

### ISSUE THREAD

**Issue by Limraj** [SCADA-LTS/Scada-LTS#2124]
**Description**
Adding report data to the test e-mail.

**Screenshot**
![Screenshot 2022-03-03 at 09 06 46](https://user-images.githubusercontent.com/35842300/156522834-764e2b59-c563-4254-bd0e-8f2a4a4d9a18.png)

**Spec:**
 - Scada Version 2.7.1

**Comment by ga7x** [comment]
In the old UI, checking the checkboxes: "Email report", "Include tabular data" and "Data in .zip format" also does not send a report with data. Sending a test email report sends an empty email. It works the same on the old UI as on the new UI. Sending a test report also does not add report data. I'm closing the issue.
