### ISSUE TITLE
I have a problem with 2.7.9. What version of tomcat did you test with? 

### ISSUE THREAD

**Issue by socialpercon** [SCADA-LTS/Scada-LTS#2145]
Scada-LTS\src\org\scada_lts\dao\error\CustomSQLEroorCodesTranslator.java:3:24
java: package javax.annotation does not exist

i try include servlet-api.jar
but i can't solve that

Is there a docker version 2.7.9 available?

**Comment by socialpercon** [comment]
i solved using jdk 1.8, tomcat 8.5.7

**Comment by SoftQ** [comment]
Hello, we recommend Java 11.
