### ISSUE TITLE
Can buttons work on Synoptic Panel?

### ISSUE THREAD

**Issue by nadeda** [SCADA-LTS/Scada-LTS#2150]
If i can, how do i create a button on synoptic panel?

**Comment by Limraj** [comment]
Hi @nadeda, we have presentations on this issue:
https://www.youtube.com/watch?v=1za1GMlaUJk

We encourage you to subscribe to our youtube channel [Scada-LTS](https://www.youtube.com/channel/UCpdS61DC09NDlA11k5lfriQ) and to use Scada-LTS.
Best wishes.
