### ISSUE TITLE
Wrong status on new cmp components

### ISSUE THREAD

**Issue by grzesiekb** [SCADA-LTS/Scada-LTS#2159]
**Describe the bug**
Wrong status on new cmp components

**To Reproduce**
Upload the project from the attachment and check whether the statuses are the same on the old and the new component
**Expected behavior**

**Screenshots**
should display the status PLS-Hand not Auto
![Screenshot_2022-04-04_07-31-41](https://user-images.githubusercontent.com/1280575/161485747-41325761-0f10-42ee-807d-755626609a5a.png)

[wrong-status.zip](https://github.com/SCADA-LTS/Scada-LTS/files/8409360/wrong-status.zip)

**Comment by Limraj** [comment]
![Screenshot 2022-04-04 at 15 34 36](https://user-images.githubusercontent.com/35842300/161555527-769e9d46-4d5c-42e2-bddb-0c1d1bd58a92.png)
![Screenshot 2022-04-04 at 15 35 15](https://user-images.githubusercontent.com/35842300/161555667-43b5e841-98ce-449a-b090-354099929129.png)
![Screenshot 2022-04-04 at 15 35 40](https://user-images.githubusercontent.com/35842300/161555743-2ddc219c-b006-4183-ab16-69768b8a29c5.png)
![Screenshot 2022-04-04 at 15 36 02](https://user-images.githubusercontent.com/35842300/161555814-afe14b96-6efc-4446-b79d-f2556f35c493.png)
![Screenshot 2022-04-04 at 15 36 27](https://user-images.githubusercontent.com/35842300/161555898-1cd35459-b3d8-4b97-a295-f000f407cd0c.png)
![Screenshot 2022-04-04 at 15 36 47](https://user-images.githubusercontent.com/35842300/161555966-328c5eee-b602-4135-a371-8bc131aa97a8.png)

**Comment by Limraj** [comment]
@grzesiekb Can we close this issue?
