### ISSUE TITLE
Update in production

### ISSUE THREAD

**Issue by marcosbotaro** [SCADA-LTS/Scada-LTS#2176]
It is always difficult to do a SCADA update in production.
A tool for that would be interesting.

**Comment by SoftQ** [comment]
Thank You for your request.

Please consider to contact us for commercial support for Your production
installation. Not only  You make sure Your installation is profesionally
maintained, but it it is the way to support the Scada-LTS project and
community as well.

Technically, the upgrade is no more complicated than as with any other web
application deployed in Tomcat. There is, however a database migration,
which  should be tested and verified for Your configuration before
proceeding with it on production.
