### ISSUE TITLE
Problems with Scada installation (2.6.15)

### ISSUE THREAD

**Issue by marcosbotaro** [SCADA-LTS/Scada-LTS#2197]
Good Morning.
I ran the SCADA installation according to the procedure described in this link: [Installation tutorial](https://github.com/SCADA-LTS/Scada-LTS/wiki/Scada-LTS-Linux-installation-tutorial)

Unable to run the application. I'm making the log available through the pastebin link: [Error log](https://pastebin.com/ifHchJX5)

I recently followed through other channels people who encountered the same problems in other versions, and the use of DOCKER was pointed out as a solution.
I believe there must be another option.

**Comment by Limraj** [comment]
Hello,
looks like you have a invalid war file, try downloading and installing again:
https://github.com/SCADA-LTS/Scada-LTS/releases/tag/v2.6.15

Best wishes

**Comment by marcosbotaro** [comment]
Hello.
I checked the file and it matches.
`root@ges-srv11:~# md5sum /var/lib/tomcat9/webapps/ScadaBR.war
154df3e1697de6ea998af69752b1b3b6  /var/lib/tomcat9/webapps/ScadaBR.war
root@ges-srv11:~#`
Below I share the images.
[File 2](https://ibb.co/qygZM46)
[File 1](https://ibb.co/jbtnS5S)

**Comment by Limraj** [comment]
In log is file:
file:/usr/share/tomcat9/lib/activation.jar
There is a problem with this file.

**Comment by marcosbotaro** [comment]
It's OK.
So it worked, my suggestion is to add this information to the documentation.

**Comment by Limraj** [comment]
Hello,
https://github.com/SCADA-LTS/Scada-LTS/wiki/Scada-LTS-Linux-installation-tutorial

We added a point like this:
`Add files from [that directory](https://github.com/SCADA-LTS/Scada-LTS/tree/develop/tomcat/lib) to tomcat /usr/share/tomcat9/lib/ libs.`

He's about those libs for tomcat.
Confirm if it's okay. If it's okay then I'll close the issue.

Best wishes.

**Comment by marcosbotaro** [comment]
Hello!
It's OK.
Thanks!
