### ISSUE TITLE
MQTT Protocol support / subscribe to a MQTT Broker(s)

### ISSUE THREAD

**Issue by hjbleier** [SCADA-LTS/Scada-LTS#2218]
Is there any plan to support MQTT in the future. It is getting popular with IoT devices because it has a low resources requirement and now that the Industrial PLC manufacture OPTO22 is pushing it as a site to site protocol because of it's low bandwidth requirements it would really be helpful to have ScadaLTS support it. Plus it can be secured with login and encryption to make it pretty secure for moving data across unsecured networks/pushing data to a cloud service.

Link to checkout what I am describing:
https://info.opto22.com/opcua-to-mqtt-bridge

Thank you

**Comment by Limraj** [comment]
Hello @hjbleier,
this is the plan, we want to do it using the plc4x library. Here the issue: #2120 
Which version this extension will come in may still change.

Best wishes,
Kamil Jarmusik
