### ISSUE TITLE
[mysql-cj-abandoned-connection-cleanup] 

### ISSUE THREAD

**Issue by grzesiekb** [SCADA-LTS/Scada-LTS#2254]
**Describe the bug**
[mysql-cj-abandoned-connection-cleanup] 

**To Reproduce**
1. start SCADA

**Expected behavior**
SCADA's correct start

**Screenshots**

![Screenshot_2022-06-06_13-21-38](https://user-images.githubusercontent.com/1280575/172151574-20e6cebb-1330-48f9-96fd-7524e4b9ac87.png)

**Comment by Limraj** [comment]
Key data such as version is missing. 
We are installing scada on prod, dev server(v2.6.15) and test server(v2.6.17), and at work locally and the application is running, so I'm confused.
@grzesiekb If you're having trouble getting scady running, it's best to contact the team before creating an issue.
