### ISSUE TITLE
Fixed getCacheEntry failed: Cache service responded with 503

### ISSUE THREAD

**Issue by Limraj** [SCADA-LTS/Scada-LTS#2259]
**Description**
There was a problem with the actions/cache@v2 

There is a problem loading the war file to the cache using the actions/cache@v2 action:
![Screenshot 2022-06-13 at 10 17 18](https://user-images.githubusercontent.com/35842300/173317951-a05bf5eb-f17e-49ba-8f5e-8030b0503586.png)

Which leads to the error:
![Screenshot 2022-06-13 at 10 17 48](https://user-images.githubusercontent.com/35842300/173318102-fd3f1c35-e898-4d13-a132-bf5406826eb0.png)

**Links**
https://github.com/bahmutov/npm-install/issues/80
https://github.com/actions/cache/issues/698
https://github.com/actions/cache/issues/820

https://github.com/marketplace/actions/cache-anything-new
https://github.com/actions/cache
https://www.githubstatus.com/

**Comment by Limraj** [comment]
up version to v3 not work

**Comment by RWilliams-MicronAgritech** [comment]
> up version to v3 not work ![Screenshot 2022-06-13 at 11 29 59](https://user-images.githubusercontent.com/35842300/173323881-e5339d79-3c0c-4417-846d-4d4863ff9795.png)
> 
> edit: up version: *actions/checkout from v2 to v3 *actions/setup-node from v1 to v3
> 
> same problem

I use checkout v2, and my actions are now running.

`    steps:
    - uses: actions/checkout@v2
      name: Use Node.js ${{ matrix.node-version }}
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        # cache: 'npm'`
