### ISSUE TITLE
ERROR in docker-compose up with docker-compose.yml

### ISSUE THREAD

**Issue by rvbatista** [SCADA-LTS/Scada-LTS#2268]
**Describe the bug**
got this error after docker-compose up with docker-compose.yml from https://github.com/SCADA-LTS/Scada-LTS/wiki
ERROR: manifest for scadalts/scadalts:master not found: manifest unknown: manifest unknown

**To Reproduce**
1. download docker-compose.yml from https://github.com/SCADA-LTS/Scada-LTS/wiki
2. run docker-compose up
3. wait.

**Expected behavior**
containers running.

**Desktop (please complete the following information):**
 - OS: ubuntu 18.04

**Additional context**
running in proxmox.

**Comment by rvbatista** [comment]
Had to modify docker-compose.yml from:
        image: scadalts/scadalts:master
to:
        image: scadalts/scadalts:v2.6.17

**Comment by Limraj** [comment]
Hello,
I corrected the file from the wiki, you can use the tag latest. I would be grateful for confirmation if it is okay.

Best wishes.
