### ISSUE TITLE
HTTP Receiver not working

### ISSUE THREAD

**Issue by odenisnobre** [SCADA-LTS/Scada-LTS#2333]
Hello,

I'm trying to use the HTTP Receiver datasource but I'm not having success.
After configured http does not do any reading:

![image](https://user-images.githubusercontent.com/8119694/191547442-f9595930-5b11-4cb9-945c-1bc290b0b2bc.png)

The url of the my application is: http://192.168.0.150:8081/Scada-LTS

I am using the follow syntax for send values:
http://192.168.0.150:8081/Scada-LTS/httpds?teste/teste=12

**Comment by Limraj** [comment]
Hello,
1. This link cannot be opened;
2. We probably don't support '*', you need to enter the address/localhost. Let me know if it works.

Best wishes.

**Comment by Limraj** [comment]
![Screenshot 2022-09-21 at 18 33 25](https://user-images.githubusercontent.com/35842300/191560846-3ba032c5-32b9-42b1-a273-6e6d5a04bad0.png)
And work url:
![Screenshot 2022-09-21 at 18 33 53](https://user-images.githubusercontent.com/35842300/191561022-70aa3b7a-9fba-4d5b-9d54-a38b1b6e0420.png)

**Comment by odenisnobre** [comment]
Return this error:
![image](https://user-images.githubusercontent.com/8119694/191563147-d7e83e08-ea5d-47ab-afb6-95aba3477aa1.png)

**Comment by Limraj** [comment]
@odenisnobre ?

**Comment by odenisnobre** [comment]
I'm finding that the ScadaBR endpoint is not available.

**Comment by Limraj** [comment]
You can't see what endpoint you are trying to trigger...

If you need mqtt communication, it is version 2.7.2, actual released is 2.6.17 and prerelease 2.7.1/2.7.1.1, next release 2.7.2.

**Comment by odenisnobre** [comment]
What I really need is MQTT communication.

![image](https://user-images.githubusercontent.com/8119694/191565607-99468168-3a48-4751-905d-c9223f3f17ac.png)

**Comment by Limraj** [comment]
Okay. The final version 2.7.2 will be created in a few days and if you want, you can help us test this mqtt client, what do you say?

As for the Receiver, however, it would be worth getting to the working configuration, of course you should have Scada-LTS in the address. You just need to keep the following order.

First you need to enable listening in, in first tab:
![Screenshot 2022-09-21 at 19 18 45](https://user-images.githubusercontent.com/35842300/191569829-4875bca4-4340-4671-b2b6-91ad986413c0.png)

And then call that endpoint, in second tab:
http://192.168.0.150:8081/Scada-LTS/httpds?teste/teste=12

On the first tab, you should see something like this:
![Screenshot 2022-09-21 at 19 20 23](https://user-images.githubusercontent.com/35842300/191570134-532a653d-2672-4934-a8e1-2304c83968d8.png)

If it works, it's worth closing the topic. If not, we will consider further.

**Comment by odenisnobre** [comment]
When I call the link, it goes to the login screen.

As for the MQTT test I do the tests without problem.

**Comment by Limraj** [comment]
But what do you get when you call it up in your browser?
How did you launch the applications?
I understand that you are using docker-compose?

**Comment by odenisnobre** [comment]
I used docker-compose yes.
When I make the request it redirects to the login screen

**Comment by odenisnobre** [comment]
https://user-images.githubusercontent.com/8119694/191575577-883b7735-58ae-44df-ab1b-d31f78985e6c.mp4

**Comment by Limraj** [comment]
You must be logged in to the application. :)

**Comment by Limraj** [comment]
Because you open in two browsers, I think? Do it yourself in tabs. Just open two tabs, one listening in one, and a rest api in the other.

**Comment by Limraj** [comment]
Do exactly what I write:
1. Open chrome or firefox;
2. You have one tab, open the other tab;
3. In one, login the application and start listening;
4. In the second, copy the address from the first tab to 'Scada-LTS' and add "/httpds?teste/teste=12" (/Scada-LTS/httpds?teste/teste=12)
5. Go back to the first tab;

**Comment by odenisnobre** [comment]
I understood.

![image](https://user-images.githubusercontent.com/8119694/191578886-1e8b64d2-51ca-49c8-9c03-32e27cc12c80.png)

It worked out.
Then you have to be logged into the application.

In another docker image I tested you don't need to login.

**Comment by Limraj** [comment]
Okej, so it works?

**Comment by odenisnobre** [comment]
Yes. now is working.

But, How would authentication be?

**Comment by Limraj** [comment]
POST HTTP: /Scada-LTS/login.htm?username=admin&password=admin&submit=Login
And next:
/Scada-LTS/httpds?teste/teste=12

**Comment by odenisnobre** [comment]
hmmm.

OK.

I am try.

**Comment by Limraj** [comment]
@odenisnobre We close the topic?
