### ISSUE TITLE
Accent problem

### ISSUE THREAD

**Issue by Xt-Man** [SCADA-LTS/Scada-LTS#2370]
**Describe the bug**
The accents are not displayed

**To Reproduce**
1. Go to 'system settings'
2. Click on 'system language'

**Screenshots**
![image](https://user-images.githubusercontent.com/39890311/197872091-77f61150-8555-47b5-bac0-2e51351c1a68.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version [2.7.2 compiled from sources]

Is this configuration I forgot or a bug?
Thank you

**Comment by Xt-Man** [comment]
Hi, i´m using windows, gradle was calling compileJava using win-1152 charset (i don´t know why, default maybe)
so, i put 
`compileJava.options.encoding = "UTF-8"
compileTestJava.options.encoding = "UTF-8"
javadoc.options.encoding = 'UTF-8'`
in build.gradle, but just solve in some places, still searching

**Comment by Limraj** [comment]
If you find a solution, open a pull request. We will code review it.

**Comment by Xt-Man** [comment]
Hi @SoftQ 
i checked the file encodings, it´s ok
My development PC runs Windows, now i´m building a Linux enviroment to test

**Comment by Limraj** [comment]
Hi @Xt-Man,
The fix will be in version 2.7.4.1. It turned out that these errors were affected by the class from seroUtils, it performed additional conversion to utf-8, which was no longer needed in java 11.

**Comment by Xt-Man** [comment]
Oh man,
I went through this file debugging, but didn't notice the problem

one more time, thank you!
