### ISSUE TITLE
MaintenanceEventVO.java bug

### ISSUE THREAD

**Issue by Aming1967** [SCADA-LTS/Scada-LTS#2402]
in MaintenanceEventVO.java
org
private LocalizableMessage month(boolean active) {
        int day = activeday;
        if (!active)
            day = inactiveday;
        return new LocalizableMessage(months[day]);
    }
modify
private LocalizableMessage month(boolean active) {
        int day = activeMonth;
        if (!active)
            day = inactiveMonth;
        return new LocalizableMessage(months[day]);
    }

**Comment by SoftQ** [comment]
Thank You! We will correct this obvious typo bug very soon -2.7.3 or 2.7.4

**Comment by Limraj** [comment]
Fix added in version 2.7.4
