### ISSUE TITLE
Report from WatchList doesn't work

### ISSUE THREAD

**Issue by Xt-Man** [SCADA-LTS/Scada-LTS#2438]
**Describe the bug**
WatchList page (~/watch_list.shtm) has a button "Create report for this watch list", but doesn't work

**To Reproduce**
1. Go to watch_list.shtm page
2. Click on "Create report for this watch list"
3. The report page is called ~/reports.shtm?wlid=1, but datapoints from this wl are not included

**Expected behavior**
The datapoints from watch list must be included

**Screenshots**
![image](https://user-images.githubusercontent.com/39890311/207954421-9c610a40-ca77-4cac-b82d-a05e7d2975c3.png)
![image](https://user-images.githubusercontent.com/39890311/207954786-2540362e-9c9b-4409-90f0-fa5f0bb828b7.png)

**Comment by Xt-Man** [comment]
Hi @Limraj ,

in file com/serotonin/mango/web/dwr/ReportsDwr.java, i change the method "createReportFromWatchlist" to:

    public ReportVO createReportFromWatchlist(int watchListId) {
        WatchListService watchListService = new WatchListService();
        WatchList watchList = watchListService.getWatchList(watchListId);
        if (watchList == null)
            return null;

        watchListService.populateWatchlistData(watchList);
        ReportVO report = new ReportVO();
        report.setName(LocalizableMessage.getMessage(getResourceBundle(), "common.copyPrefix", watchList.getName()));
        for (DataPointVO dp : watchList.getPointList()) {
            ReportPointVO rp = new ReportPointVO();
            rp.setPointId(dp.getId());
            rp.setColour(dp.getChartColour());
            rp.setConsolidatedChart(true);
            report.getPoints().add(rp);
        }

        return report;
    }

and solve the issue, if there is a better way to solve it, please told me
thank you

**Comment by Limraj** [comment]
Hi @Xt-Man,
If you could take a look: 
https://github.com/SCADA-LTS/Scada-LTS/pull/2439

**Comment by Xt-Man** [comment]
Hi @Limraj ,
That´s it!
Thank you
