### ISSUE TITLE
Error message on WatchList Get Chart

### ISSUE THREAD

**Issue by Xt-Man** [SCADA-LTS/Scada-LTS#2456]
**Describe the bug**
An error message appears -> "Error marshalling int: Format error converting 419.77778. See the logs for more details."

**To Reproduce**
1. On yout browser, press ctrl- to reduce the zoom to 90%
2. On WatchList, click on Get Chart
3. See error
![image](https://user-images.githubusercontent.com/39890311/210610624-82b2bfea-7e6f-4438-8d03-dce1be941120.png)

**Expected behavior**
Shows the graphic

**Additional context**
Any browser zoom (except 100%) show this error

**Comment by Xt-Man** [comment]
Hi @Limraj ,

any news about this issue?

**Comment by Limraj** [comment]
Hello @Xt-Man !
would you like to improve it? We have to deal with it...

**Comment by fabiodurao** [comment]
This error happened to me on slts 2.7.5.2 with chrome, but I was using zoom in the browser, when I went back to 100% I didn't have the problem anymore and the graph was built normally.

**Comment by Xt-Man** [comment]
Hi @fabiodurao , exactly! The error message appears only on zoom != 100.

I will create a merge request with the fix

**Comment by Xt-Man** [comment]
Hi, @Limraj @fabiodurao 
Done! Pull Request created
[https://github.com/SCADA-LTS/Scada-LTS/pull/2519]

Thanks
