### ISSUE TITLE
How can i implements sum(previous multiple datapoint )  on graphic view?

### ISSUE THREAD

**Issue by nadeda** [SCADA-LTS/Scada-LTS#2469]
i don't know how can i insert multiple datapoint calcuate data show on graphic view.
i have two virtual data.
virtual data 1
virtual data 2

i want to show on graphic view.
virtual data 1 + virtual data2

but, i only know with server side script 1 datapoint.
how can i show that...
i guess scripts or sql.
but that is very difficult for me.
can i get detail example for scripts or sql?

**Comment by Limraj** [comment]
Hi @nadeda,
1. If you want to sum the values ​​of two different points then you can use a Meta Data Source with a point where you set the points of interest in the context and you can sum the values ​​of those points from the context and then display that meta data point on the Graphical View.
2. If you want to display the value of any point, you can use the Simple Point Component, there in the form you select the point you want to display.

If you need support, I encourage you to write to:
[scadalts-support@softq.pl](mailto:scadalts-support@softq.pl)

Best regards,
Kamil Jarmusik
