### ISSUE TITLE
Embebed Chrome in SCADA

### ISSUE THREAD

**Issue by alvarogaro** [SCADA-LTS/Scada-LTS#2470]
* Hi, I'm using a SCADA software, i want to have Chrome embebed inside SCADA because it use IE by default but I don't know how to do it

**Comment by Limraj** [comment]
Hi @alvarogaro,
I don't understand what you want to achieve, you'd have to describe your specific case to me, maybe with screenshots. 

Best regards,
Kamil Jarmusik
