### ISSUE TITLE
Unable to use .svg to Synoptic Panel

### ISSUE THREAD

**Issue by sheza160217** [SCADA-LTS/Scada-LTS#2474]
Hi,

I have installed Scada-LTS on a virtual machine using docker.

_Installation: Docker on proxmox LXC container
Image: release-2.7.5
Method: docker-compose_

Issue: Followed your tutorial on Youtube for Synoptic Panels. When I try to upload a .svg fiel created in Inkscape to Synoptic Panel, there is a prompt to confirm adding the image. But there are no other details to assign any virtual point data to the svg components. The svg image is shown on the Synoptic Panel as a static image.

Thanks for your guidance.

**Comment by Limraj** [comment]
Hi @sheza160217,
1. Which graphic did you try to upload?

2. In the video you have information that after uploading the image you need to additionally select this panel from the list, did you do this step?

Regards,
Kamil Jarmusik

**Comment by sheza160217** [comment]
@Limraj :

I have a simple .svg file created with Inkscape.
![tank2](https://user-images.githubusercontent.com/88371345/218511050-321b9df2-b29b-4856-b67d-ad2e258e22bf.svg)

The notification says "Added successfully".

After uploading the .svg file, when I click on the pencil icon the below window is all that appears:
![screenshot](https://user-images.githubusercontent.com/88371345/218513359-03f0b0d8-73fe-4b68-a9f9-08a93d5d17a3.png)

What could be wrong?

Thanks for your help.

**Comment by Limraj** [comment]
![Screenshot 2023-02-13 at 17 38 19](https://user-images.githubusercontent.com/35842300/218517391-315069b8-ca1e-49fb-9dc3-d62af16a6112.png)
I managed to add this graphic, as I said in point 2, after uploading the graphic you have to select the panel again in this select:
![Screenshot 2023-02-13 at 17 39 39](https://user-images.githubusercontent.com/35842300/218517705-b3fec90b-9fd4-4954-aa55-7e046549868d.png)

**Comment by Limraj** [comment]
But there is an error, if you don't enter a name, then this panel is in this list, but without any name etc, it looks like it's not there, but there. There should be a validation on the frontend side to force entering the name of the panel:

![Screenshot 2023-02-13 at 17 43 43](https://user-images.githubusercontent.com/35842300/218518702-40264f72-4ba9-4da9-8503-aa808889f865.png)


If you described the scenario in this task so that this error could be reproduced, there is a chance that someone will correct it, although I must admit that it will not be a priority. Adding an image only works if you don't set a name then it will show up without a name in this list.

**Comment by sheza160217** [comment]
@Limraj :

Sorry for taking time to reply. I have tried it again. This time with all the steps you have mentioend in above posts.

Still I do not get the complete diaglog to bind the data points. I have also reinstalled on a new LXC container with docker. I can confirm the behaviour is the same.

Is it casued by the docker image 2.7.5? Or something else? Not sure.

Thanks.

**Comment by Limraj** [comment]
Hi @sheza160217,
I understand. This corrected svg: 
![milk2](https://user-images.githubusercontent.com/35842300/218881618-3b6cc0d9-8e22-4736-83c3-e7e4d8ff92a2.svg)


Okay, for this field to work, the id must match the regex:
`SLTS_((waterlevel|fan|point|state|valve)_\d|(_(background\b|background_right|background_left|value)))+\b`
So it is not enough that it starts with SLTS_, it must be followed by one of the 5 keywords (waterlevel, fan, point, state, valve), and at the end there must be a number, and it may or may not be: _background, _background_left, _background_right or _value, moreover, components with such an end are associated with one device/object.

Based on these ids, the component determines the function of the given field. Examples of valid ids:
(All are for waterlevel_1)
SLTS_waterlevel_1
SLTS_waterlevel_1_background

(All are for valve_1)
SLTS_valve_1
SLTS_valve_1_background_left,
SLTS_valve_1_background_right,
SLTS_valve_1_value

SLTS_point_1

(All are for fan_1)
SLTS_fan_1
SLTS_fan_1_background
SLTS_fan_1_value

However, this is an experimental feature and from what I can see there are problems with it.
It seems that fan, valve and waterlevel are working, there is a problem with point and state. There is also a problem with where fields ending in _value are displayed.

**Comment by Limraj** [comment]
Hi @sheza160217,
The point_1/state_1 fields also need point_1_value/state_1_value. Then it works, the values ​​are refreshed and in the right place. 

This corrected svg: 
![milk2](https://user-images.githubusercontent.com/35842300/219309737-d99edf2c-ee0f-463e-a260-f09a3f437250.svg)

Based on these ids, the component determines the function of the given field. Examples of valid ids:
(All are for point_1)
SLTS_point_1
SLTS_point_1_value

(All are for state_1)
SLTS_state_1
SLTS_state_1_value

We'll be back with more information.

**Comment by Limraj** [comment]
Hi @sheza160217,
So it is important to fulfill this formula for ids of text fields for ids with: value, label, and polygons field for ids with: background, background_left, background_right and main field (examples: SLTS_point_2, SLTS_valve_3, SLTS_waterlevel_1). 

Additionally, text fields must be unflow: 
![Screenshot 2023-02-17 at 12 07 17](https://user-images.githubusercontent.com/35842300/219632885-8590ebd3-e1c0-4648-b40e-b725d021b3f3.png)

SLTS_waterlevel_1
SLTS_waterlevel_1_background

SLTS_valve_1
SLTS_valve_1_background_left,
SLTS_valve_1_background_right,
SLTS_valve_1_value
SLTS_valve_1_label

SLTS_point_1
SLTS_point_1_value
SLTS_point_1_label

SLTS_fan_1
SLTS_fan_1_background
SLTS_fan_1_value

SLTS_point_1
SLTS_point_1_value
SLTS_point_1_label

SLTS_state_1
SLTS_state_1_value
SLTS_state_1_label

Corrected svg:
![milk](https://user-images.githubusercontent.com/35842300/219638835-cb269bda-c424-4c14-be5d-e90d4e78905d.svg)

You can use Group/Layout to organize your views, they shouldn't break anything.
![Screenshot 2023-02-17 at 12 31 50](https://user-images.githubusercontent.com/35842300/219640919-a8fa24e3-a1b3-452d-9b2e-62744d0180de.png)
![Screenshot 2023-02-17 at 12 32 32](https://user-images.githubusercontent.com/35842300/219641159-07b33e3f-d8c6-482b-aeb2-a3982d6156ff.png)
![Screenshot 2023-02-17 at 12 33 06](https://user-images.githubusercontent.com/35842300/219641336-0db475cb-a3ec-465a-949b-8b875320b41e.png)


Let me know if this solved the problem and we can close the issue.

**Comment by sheza160217** [comment]
@Limraj :
Thanks for taking time out to reply. As I have been haviong less time to test, I have tested now and below are the results:

**_Docker Image: release-2.7.5_**
I am able to import the svg image as you had suggested. Scada-LTS creates the screen as expected. But when I click the pencil icon, the icon freezes and nothing happens.

**_Docker Image: scadalts:latest_**
The prompt to move to newer interface does not appear at all.

I have working the old interface with the "latest" docker image and so far it is good. I am working with 2 versions of docker images in parallel and if there are any major differences I will post back.

We can close this issue with this.

Thanks for your help.

**Comment by Limraj** [comment]
@sheza160217 
Does it work or are there any problems? There should be no problems with the edit button... it's worth checking.
Describe exactly what steps led to this suspension of editing. I import the corrected svg and there is no problem with editing and pinning the points. Maybe you imported a different svg? 
There are no panels in the latest version 2.6.18, so you won't find these features there.

**Comment by sheza160217** [comment]
@Limraj :+1: 

Ofcourse I imported the wrong .svg. I tries with the one in the above post and now it works.

Let me study the .svg file you provided. Thank you so very much!!!

**Comment by Limraj** [comment]
You report a problem, so we try to help, nothing more. If you write about a bug, a scenario that will allow us to reproduce the problem is valuable to us, then we can think about what we will do with it, etc. That's all I'm after. Take care.

**Comment by Limraj** [comment]
Hi @sheza160217,
If you don't use these panels, use the latest release from the tag: v2.6.18. Version 2.7.5 is not yet released and will change. 
After release/prerelease 2.7.5 version then v2.7.5 tag will be available. Each released version has a tag: v{version}; (e.g. just v2.6.18, v2.7.4.1)

Regards,
Kamil Jarmusik
