### ISSUE TITLE
Inconsistency between hierarchy added by UI and by json

### ISSUE THREAD

**Issue by fabiodurao** [SCADA-LTS/Scada-LTS#2484]
Scada-LTS 2.7.4.1 - Manual instalation

1. On the hierarchy screen, I created a test folder, dragged a datapoint into this folder and it was automatically saved;
![image](https://user-images.githubusercontent.com/38673539/227078482-c81c8004-7e50-4e44-b5f4-cb6e15bbf75d.png)
2. On the import/export screen, I checked the hierarchy checkbox, exported the json;
3. I added the XID of a variable within the json relative to the created folder;
![image](https://user-images.githubusercontent.com/38673539/227078779-8b56f312-5116-4ae0-9590-e1aef2fc206d.png)
4. Refreshing the watch list screen, the hierarchy modification was accepted;
![image](https://user-images.githubusercontent.com/38673539/227078964-3d349e52-0a32-41f6-9162-cef520ee5574.png)
5. Updating the hierarchy screen, the modification does not appear, even when clicking on the refesh icon available on this screen.
![image](https://user-images.githubusercontent.com/38673539/227079094-7e2f46ea-f9e2-4abc-b17b-82e6e4732990.png)

**Comment by fabiodurao** [comment]
Update: A few minutes after making the change via json, the hierarchy screen updated, I don't understand why it took so long.
Maybe it's not the time, it's the fact that I created one more folder and updated the structure.

**Comment by Limraj** [comment]
Hi @fabiodurao,
I looked at the code and it looks like the structure is updated every 10min, but the refresh button should force this update...

The refresh rate is configurable in the env.properties file:
abilit.CRONE_UPDATE_CACHE_POINT_HIERARCHY=0 0/10 * * * ?

**Comment by fabiodurao** [comment]
ok, good to know it's only a matter of time to update.

**Comment by Limraj** [comment]
#2014
