### ISSUE TITLE
Map Volume Docker Application

### ISSUE THREAD

**Issue by odenisnobre** [SCADA-LTS/Scada-LTS#2492]
Is it possible to map the application completely in a docker volume?
I say the files from the assets folder, uploads and etc.

**Comment by Limraj** [comment]
Hi @odenisnobre,
what would you like to achieve in this way? 

You can experiment with the volumes configuration in the [docker-compose.yml](https://github.com/SCADA-LTS/Scada-LTS/blob/develop/docker-compose.yml) file:
[volumes-in-docker-compose](https://devopscell.com/docker/docker-compose/volumes/2018/01/16/volumes-in-docker-compose.html)
[volumes](https://docs.docker.com/storage/volumes/)

Regards,
Kamil Jarmusik

**Comment by odenisnobre** [comment]
Actually I would like to have 'external' access to the application files.
To be able to customize some items like color, font, things like that.

The command that is in docker-compose has only mapped the logs.

**Comment by odenisnobre** [comment]
I will close this case because I think I have already clarified the doubts.

**Comment by Limraj** [comment]
Hi @odenisnobre,
You can do something like:
1. Stop scadalts container. To volumes for scadalts service add:
           - ./tomcat_webapps:/usr/local/tomcat/webapps:rw
       
![Screenshot 2023-03-27 at 14 48 00](https://user-images.githubusercontent.com/35842300/227944409-91227170-d207-4bcb-87c4-e832473eaf8f.png)

2. In the place where you have placed the docker-compose.yml file, there is a create folder tomcat_webapps;
3. You download the Scada-LTS application, e.g. version beta [v2.7.5.1](https://github.com/SCADA-LTS/Scada-LTS/releases/download/v2.7.5.1/Scada-LTS.war) or stab latest [v2.6.18](https://github.com/SCADA-LTS/Scada-LTS/releases/download/v2.6.18/ScadaBR.war)
4. Transfer the downloaded file to tomcat_webapps
5. You start database and scadalts container.

This should cause the application to be deployed in folder tomcat_webapps, you will have all the contents of the application in the Scada-LTS/ScadaBR folder. If you change these files, the changes should be visible in the application.

Regards,
Kamil Jarmusik

**Comment by Limraj** [comment]
Hi @odenisnobre,
You can do something like:
1. Stop scadalts container. To volumes for scadalts service add:
           - ./tomcat_webapps:/usr/local/tomcat/webapps:rw
       
![Screenshot 2023-03-27 at 14 48 00](https://user-images.githubusercontent.com/35842300/227944409-91227170-d207-4bcb-87c4-e832473eaf8f.png)

2. In the place where you have placed the docker-compose.yml file, there is a create folder tomcat_webapps;
3. You download the Scada-LTS application, e.g. version beta [v2.7.5.1](https://github.com/SCADA-LTS/Scada-LTS/releases/download/v2.7.5.1/Scada-LTS.war) or stab latest [v2.6.18](https://github.com/SCADA-LTS/Scada-LTS/releases/download/v2.6.18/ScadaBR.war)
4. Transfer the downloaded file to tomcat_webapps
5. You start database and scadalts container.

This should cause the application to be deployed in folder tomcat_webapps, you will have all the contents of the application in the Scada-LTS/ScadaBR folder. If you change these files, the changes should be visible in the application.

Regards,
Kamil Jarmusik

**Comment by odenisnobre** [comment]
That's exactly what I needed and I ended up getting it done by testing it over and over again.

Thank you very much.

**Comment by Limraj** [comment]
@odenisnobre Just be careful with the version of the app you're using. The database structure of version 2.6.18 is different than 2.7.5.1, so if you launch the beta on the database of version 2.6.18, you will not be able to go back to version 2.6.18. 
It's best to use the version from the docker tag. 
If you want to go back to the previous behavior, just remove the entry from volumes and restart the container.
