### ISSUE TITLE
scadalts-ui dependency @min-gb/vuejs-components is not in this registry

### ISSUE THREAD

**Issue by lanicc** [SCADA-LTS/Scada-LTS#2505]
**Describe the bug**
scadalts-ui dependency @min-gb/vuejs-components is not in this registry

**To Reproduce**

run `npm install`

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@min-gb%2fvuejs-components - Not found
npm ERR! 404 
npm ERR! 404  '@min-gb/vuejs-components@0.0.7' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Comment by Limraj** [comment]
Hi @lanicc,
try:
1. git checkout develop, or rollback:
![Screenshot 2023-04-11 at 12 11 03](https://user-images.githubusercontent.com/35842300/231129598-c41fea9a-79e3-454a-9e09-c726bc44f87e.png)

2. git pull;

**Comment by Limraj** [comment]
@lanicc Does it work for you or can we close the topic?

**Comment by lanicc** [comment]
> @lanicc Does it work for you or can we close the topic?

Thanks a lot.It's worked

**Comment by stly** [comment]
@lanicc do u run this program in idea?
i deploy it but not work. 
![image](https://user-images.githubusercontent.com/10585265/233818118-f22048d3-0d0d-4624-b074-3febc0f9de47.png)
![image](https://user-images.githubusercontent.com/10585265/233818132-7bb539cd-41b3-4109-9ed0-2065fbab705a.png)
