### ISSUE TITLE
Create Data/Point Source with API

### ISSUE THREAD

**Issue by odenisnobre** [SCADA-LTS/Scada-LTS#2518]
I have to create 10 points source(Modbus TCP) where what changes is only the end of the ip xxx.xxx.xxx.110@119

And the points are the same records and names for each point source.

Would it be possible to create these points sources and data points via API or in some automated way?

**Comment by Limraj** [comment]
Hi @odenisnobre,
you can do this using Postman: https://www.postman.com/

**1. Login** 
`http://localhost:8080/ScadaBR/api/auth/admin/admin GET`
or
`http://localhost:8080/ScadaBR/login.htm?username=admin&password=admin&submit=Login POST`
**2. Create new datasource:**
`http://localhost:8080/ScadaBR/api/datasource POST`
example body:
```
{
    "xid": "DS_7973799",
    "name": "modbus_ip_1",
    "type": 3,
    "enabled": true,
    "connectionDescription": "common.default",
    "updatePeriodType": 1,
    "updatePeriods": 5,
    "quantize": false,
    "timeout": 500,
    "retries": 2,
    "contiguousBatches": false,
    "createSlaveMonitorPoints": false,
    "maxReadBitCount": 2000,
    "maxReadRegisterCount": 125,
    "maxWriteRegisterCount": 120,
    "transportType": "TCP",
    "host": "localhost",
    "port": 502,
    "encapsulated": false,
    "createSocketMonitorPort": false
}
```
**3. Update datasource:**
`http://localhost:8080/ScadaBR/api/datasource PUT`
body:
```
{
    "id": 1,
    "xid": "DS_7973799",
    "name": "modbus_ip_1",
    "type": 3,
    "enabled": true,
    "connectionDescription": "common.default",
    "updatePeriodType": 1,
    "updatePeriods": 5,
    "quantize": false,
    "timeout": 500,
    "retries": 2,
    "contiguousBatches": false,
    "createSlaveMonitorPoints": false,
    "maxReadBitCount": 2000,
    "maxReadRegisterCount": 125,
    "maxWriteRegisterCount": 120,
    "transportType": "TCP",
    "host": "localhost",
    "port": 502,
    "encapsulated": false,
    "createSocketMonitorPort": false
}
```
**4. Create datapoint:**
range:
Coil status - 1
Input status - 2
Holding register - 3
Input register - 4
`http://localhost:8080/ScadaBR/api/datapoint POST`
body:
```
{
    "xid": "DP_6352",
    "name": "dp_2",
    "description": null,
    "enabled": true,
    "dataSourceTypeId": 3,
    "dataSourceId": 5,
    "deviceName": "modbus_ip_1",
    "pointLocator": {
        "dataSourceTypeId": "3",
        "dataTypeId": 2,
        "settable": true,
        "range": 3,
        "modbusDataType": 2,
        "slaveId": 1,
        "slaveMonitor": false,
        "socketMonitor": false,
        "offset": 0,
        "bit": 0,
        "registerCount": 0,
        "charset": "ASCII",
        "settableOverride": true,
        "multiplier": 1.0,
        "additive": 0.0,
        "relinquishable": false
    },
    "datasourceName": "modbus_ip_1",
    "dataSourceXid": "DS_797379",
    "typeId": 1,
    "settable": true
}
```
**5. Update datapoint:**
`http://localhost:8080/ScadaBR/api/datapoint PUT`
body:
```
{
    "id": 12,
    "xid": "DP_6352",
    "name": "dp_2",
    "description": null,
    "enabled": true,
    "dataSourceTypeId": 3,
    "dataSourceId": 5,
    "deviceName": "modbus_ip_1",
    "pointLocator": {
        "dataSourceTypeId": "3",
        "dataTypeId": 2,
        "settable": true,
        "range": 3,
        "modbusDataType": 2,
        "slaveId": 1,
        "slaveMonitor": false,
        "socketMonitor": false,
        "offset": 0,
        "bit": 0,
        "registerCount": 0,
        "charset": "ASCII",
        "settableOverride": true,
        "multiplier": 1.0,
        "additive": 0.0,
        "relinquishable": false
    },
    "datasourceName": "modbus_ip_1",
    "dataSourceXid": "DS_797379",
    "typeId": 1,
    "settable": true
}
```

Regards,
Kamil Jarmusik

**Comment by odenisnobre** [comment]
Wow, sensational.
I'll try.

**Comment by Limraj** [comment]
It is in version 2.7.5.2

dataSourceTypeId  = 3 (MODBUS_IP)

This feature is currently limited and you can create the following Data Source this way:
dataSourceTypeId  = 1 (VirtualDataSource)
dataSourceTypeId  = 3 (ModbusIpDataSource)
dataSourceTypeId  = 5 (SnmpDataSource)
dataSourceTypeId  = 9 (MetaDataSource)

"Wow, sensational." I do not fully understand?

**Comment by odenisnobre** [comment]
LOL.
I meant that this is very interesting and very useful.

**Comment by Limraj** [comment]
@odenisnobre 
I think your reaction is overreacting. I'm just asking what you meant by that, it could have been a mockery. I try to help as much as I can, but I have no influence on whether you do it according to the instructions or in your own way. Generally, if something does not work for you as expected, it is worth asking before drawing conclusions. Also take into account that my English is not the best and we communicate by text, so we can't read the intention. In such communication, a subdued form of expression is more effective.

**Comment by odenisnobre** [comment]
@Limraj 

Well, I think you misunderstood me.
My English is not the best either.
But my reaction was one of thanks rather than mockery.
Regardless of the result and conclusions, just having the possibility and having already thought about this possibility is very important.
This was my reaction, of thanks.
But in the next posts they will post only one: 'ok', 'all right'. That makes it simpler.

**Comment by Limraj** [comment]
@odenisnobre Okey. We don't have to, but that statement was a bit above the norm... It's just that it surprised me a little. I think everything is fine. Let me know if you managed to create these Data Sources and Data Points.

**Comment by odenisnobre** [comment]
Alright, I'll improve communication in the next ones.

I tested it and I still wasn't successful, it seems to me that ScadaBR is not available. I'm trying to see what's going on.

**Comment by Limraj** [comment]
@odenisnobre 
What version of Scada-LTS are you working on? Are you using postman?

**Comment by odenisnobre** [comment]
![image](https://user-images.githubusercontent.com/8119694/233375484-831233e9-749b-4c1a-9079-5ab15b54ab74.png)

**Comment by Limraj** [comment]
Are you using postman to call the API

**Comment by odenisnobre** [comment]
He doesn't, I use other resources.
But if so, I can use it.

**Comment by Limraj** [comment]
How are you calling this API?

In Postman:
1. First you need to login to Scada-LTS in Postman:
![Screenshot 2023-04-20 at 15 10 03](https://user-images.githubusercontent.com/35842300/233376294-bb8952a4-a8d2-43da-bb7e-8d02469c64ac.png)

After success login return:
![Screenshot 2023-04-20 at 15 12 32](https://user-images.githubusercontent.com/35842300/233376926-cf12fe3e-fc6e-4c3b-9aef-1f9f2a816a24.png)

2. You send a message configured to create a Data Source Modbus IP:
![Screenshot 2023-04-20 at 15 08 23](https://user-images.githubusercontent.com/35842300/233375850-66b0235e-6dae-4834-b43d-812b0fe39cc9.png)

**Comment by odenisnobre** [comment]
![image](https://user-images.githubusercontent.com/8119694/233377022-299314b9-b447-4f9a-8a48-f1b18f974399.png)

**Comment by Limraj** [comment]
If you have Scada-LTS.war deployed in tomcat then instead of ScadaBR you do Scada-LTS. Then the application is at Scada-LTS and not ScadaBR.

**Comment by odenisnobre** [comment]
It was right.
The datasource and datapoints were created via postman.
Thank you very much.
I'll try now with the tool I use based on nodejs
Thank you very much.

**Comment by Limraj** [comment]
@odenisnobre 
Do you have any more questions in this regard?
