### ISSUE TITLE
Image selection in binary component not showing up and text alignment in write button missing

### ISSUE THREAD

**Issue by fabiodurao** [SCADA-LTS/Scada-LTS#2520]
**Describe the bug**
1-In the graphic representation, when adding a binary component, in the place where the image is chosen to represent state zero and the image to represent state one, it is possible to make the selection, but a border around the image does not appear to show the selection and give visual feedback to the developer.
2-The text inside the writing button is left aligned.

**To Reproduce**
1. Go to the graphical representation, add a binary component, when selecting the images for the two states, there is no visual feedback to see which image was selected.
2. Go to the graphical representation, add a writing button component, the text inside the button will be left aligned.

**Expected behavior**
1-A visual return is expected to show the selection of images, a border around it would solve it;
2-It is expected that the text inside the button is centered alignment

**Screenshots**
![image](https://user-images.githubusercontent.com/38673539/233473621-a6e457cd-cea7-4631-8084-4c29ec1b857d.png)

**Desktop (please complete the following information):**
  - OS: Windows 10 64bit
  - Browser: Chrome 112.0.5615.49
  - Version: Scada-LTS 2.7.5.2

**Comment by Limraj** [comment]
https://github.com/SCADA-LTS/Scada-LTS/issues/2596
