### ISSUE TITLE
Fixed not emit sounds

### ISSUE THREAD

**Issue by GabrielTec251** [SCADA-LTS/Scada-LTS#2588]
I have problems with the audio output of the alarms, the alarm does not sound.

when I configure the alarms, whether light or urgent or critical, when triggered they do not emit any sound, I tested it in other browsers and enabled the permission of sites, the error persisted.

this message was translated from portuguese to english by google translator.

SCADA - LTS - 2.7.5.2
SCADA - LTS - 2.7.5.3

**Comment by Limraj** [comment]
Hi @GabrielTec251,
We haven't used this feature for a long time. Could you check if v2.6.18 has the same problem?

Regards,
Kamil Jarmusik

**Comment by GabrielTec251** [comment]
YES, have the same problem

**Comment by GabrielTec251** [comment]
in SCADABR we configured the alarms and the beep sound came from the system itself.

I tested this LTS function on windows 10 and 11, on edge and chrome.

**Comment by GabrielTec251** [comment]
![arquivos de som](https://github.com/SCADA-LTS/Scada-LTS/assets/138117880/689c0c9e-2fa1-4b1c-b215-f09016b053c2)

the files exist, it only plays the media.

**Comment by GabrielTec251** [comment]
![Capturar](https://github.com/SCADA-LTS/Scada-LTS/assets/138117880/2be948f0-9fd0-43c7-99d1-6d88ae980b19)


here is how to be in scadaBR

**Comment by Limraj** [comment]
@GabrielTec251 We will fix this in version 2.7.5.4

**Comment by fabiodurao** [comment]
To help in an additional context, ScadaBR 1.2 has also updated soundmanager to the version of this site (https://www.schillmania.com/projects/soundmanager2/doc/download/), follow the version link (http://www. wcny.org/js/soundmanager/download/soundmanagerv297a-20120318.zip)

It looks like the old version of soundmanager depended on flash, which is blocked by current browsers, and the new version relies on html5.

Even with this upgrade, in ScadaBR 1.2 it was necessary to go to the browser and click on the "i" on the left side where the url is written, and in "site settings", choose the option "sound" and "allow". To help the user, on the first access, a "help balloon"/"popup" appeared under that letter "i" with instructions for the user to enable the "sound" in his browser.

**Comment by Limraj** [comment]
Hi @fabiodurao,
this information was not necessary, I already did it yesterday. 
This was the main problem with this feature.
It also had to be adapted to the websocket that we use for the highest alarm level notification function.

Whereas a test would be helpful: https://github.com/SCADA-LTS/Scada-LTS/pull/2589

Regards,
Kamil Jarmusik

**Comment by GabrielTec251** [comment]
It is emitting sounds, however The alarm function must act in a way to "disturb" the operator, that is, there are cases in which the operator is not a few meters away from the supervisor, or even talking to a co-worker, for example. That's why the alarm must keep beeping until the operator acknowledges the alarm.
