### ISSUE TITLE
Faster loading of the Event Handlers page

### ISSUE THREAD

**Issue by Limraj** [SCADA-LTS/Scada-LTS#2601]
*Expected Behavior*
We would like the page with event handlers to load faster. You should check if some kind of lazy loading could be used, and maybe introduce a search engine.

*Actual Behavior*
With large configurations, with about 1000 handlers, loading the page takes a few to several seconds.

*Specifications*
Scada-LTS Version: <=2.7.5.3

**Comment by Patrykb0802** [comment]
Did testing on Event Handlers page loading time with versions 2.6.18 and 2.7.7.3 using same data.

Results:
 - 2.6.18 time: 16 seconds
 - 2.7.7.3 time: 8.5 seconds
