### ISSUE TITLE
Faster loading of the Data Sources List page

### ISSUE THREAD

**Issue by Limraj** [SCADA-LTS/Scada-LTS#2602]
*Expected Behavior*
Lazy loading of points in the data sources list should be introduced. Perhaps you could also not load the full Data Point data, they are not needed there.

*Actual Behavior*
The Data Source is loaded into the view along with all Data Points, which causes the view to load longer and longer, along with the size of the configuration.

*Specifications*
Scada-LTS Version: <= 2.7.5.3

**Comment by Patrykb0802** [comment]
Did testing on Data Source List loading time with versions 2.6.18 and 2.7.7.3 using same data.

Results:
 - 2.6.18 time: 14 seconds
 - 2.7.7.3 time: 6.5 seconds
