### ISSUE TITLE
docker stability issues

### ISSUE THREAD

**Issue by 2426852837** [SCADA-LTS/Scada-LTS#2604]
My computer is Win11 and SCADALTS starts normally after executing the docker-compose up command using the files provided by dockerhub. But I go to localhost:9090 and the interface keeps loading without any interface or prompt. It regularly returns localhost without sending any data. I would like to ask if this is because the docker version you provide is not stable enough?

**Comment by 2426852837** [comment]
version: '3'
services: 
    database:
        container_name: mysql
        image: mysql/mysql-server:5.7
        ports:
            - "13306:3306"
        environment: 
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
            - MYSQL_DATABASE=scadalts
        expose: ["3306"]
        volumes:
            -   ./docker/volumes/databases:/home/
    scadalts:
        image: scadalts/scadalts:latest
        ports: 
            - "9090:8080"
        depends_on: 
            - database
        expose: ["8080", "8000"]
        links:
            - database:database

**Comment by Limraj** [comment]
Hi @2426852837,
1. Questions are best asked here:
https://github.com/SCADA-LTS/Scada-LTS/discussions
You need to close this issue and add the question in the discussions;
2. Here is the current configuration file: https://github.com/SCADA-LTS/Scada-LTS/blob/develop/docker-compose.yml
3. If you see any error anything, send a screenshot.
4. First you need to start the database:
`docker-compose up database`
When the database starts then:
`docker-compose up scadalts`
[docker-compose-tutorial](https://github.com/SCADA-LTS/Scada-LTS/wiki/Scada-LTS-docker-compose-tutorial)
5. Make sure port 9090 is free, during startup you also have docker logs:
https://docs.docker.com/config/daemon/logs/

Regards,
Kamil Jarmusik
