### ISSUE TITLE
Fix possible Unreleased lock

### ISSUE THREAD

**Issue by SoftQ** [SCADA-LTS/Scada-LTS#2634]
Tracking issue reported in  https://github.com/SCADA-LTS/Scada-LTS/security/code-scanning/2166

**Comment by Limraj** [comment]
There is an unlock in the code in block finally :
```
    public boolean cancel() {
        synchronized (lock) {
            boolean result = (state == SCHEDULED);

            if (completeBeforeCancel) {
                try {
                    cancelLock.writeLock().lock();
                    state = CANCELLED;
                }
                finally {
                    cancelLock.writeLock().unlock();
                }
            }
            else
                state = CANCELLED;

            return result;
        }
    }
```
**cancelLock.writeLock().unlock();**

The only thing that could be slightly improved here is to throw lock() out of try:
https://docs.oracle.com/javase%2F7%2Fdocs%2Fapi%2F%2F/java/util/concurrent/locks/ReentrantReadWriteLock.html
