### ISSUE TITLE
erro de http 

### ISSUE THREAD

**Issue by GabrielTec251** [SCADA-LTS/Scada-LTS#2709]
**Describe the bug**
![reclmação](https://github.com/SCADA-LTS/Scada-LTS/assets/138117880/0055274d-984f-4a34-909f-e3b2f143bb98)
this is showing straight away

**Comment by Limraj** [comment]
Hi @GabrielTec251, 
This message appears if the user is, for example, logged out of the application. The session lasts 30 minutes. If you refresh the page, do you not have to log in?

Regards,
Kamil Jarmusik

**Comment by Limraj** [comment]
@GabrielTec251 
Okay, no answer, so I assume the matter is resolved. I'm closing the topic.

**Comment by GabrielTec251** [comment]
Hi, I'm sorry for the delay, but this error happens due to having inframes inside the scada lts itself, in other words, I opened a scada lts page inside another page using it as a pop up, inside an inframe
