### ISSUE TITLE
Legend occupies too much space in reports screen

### ISSUE THREAD

**Issue by GabrielTec251** [SCADA-LTS/Scada-LTS#2726]
When many variables are chosen in the report for the consolidated graph, t
[Scada-LTS.pdf](https://github.com/SCADA-LTS/Scada-LTS/files/12936713/Scada-LTS.pdf)
he legend occupies the entire area and does not show graphs

scada-lts v2.7.5.4
win 10

**Comment by GabrielTec251** [comment]
![Capturar](https://github.com/SCADA-LTS/Scada-LTS/assets/138117880/e1b0b60c-72b6-4367-8018-ee505a01e9e7)

**Comment by Limraj** [comment]
Hi @GabrielTec251,
Thank you for this report
