### ISSUE TITLE
Added Assignee function for events

### ISSUE THREAD

**Issue by Limraj** [SCADA-LTS/Scada-LTS#2746]
*Description*
I would suggest adding an 'Assignee' function that would work as follows:
1. It is only available for Active events, when acknowledge is not available;
2. <s>It has the same icon as acknowledge, but a different signature;</s> It has the other icons, Assign icon 'user plus' and Assignee icon 'user minus';
3. An Assignee column has been added to the Pending and Search tables, displaying the username and acceptance date;
4. A given event can only be assign once, by one person;
5. When it comes to notifying the highest alarm for a given user, it would work exactly like the silence function, with the difference that every user can see it;
6. Assignee events do not disappear from the pending list;
7. If the event goes to the 'Return to normal' state, then the 'Acknoledged' function is displayed and 'Assign' disappears.

Edit:

**Details**

1. We made it impossible to confirm an active event;
2. A person from the community pointed out that they need a function that confirms that a given operator has received an event, it must include who and when;
3. Hence, I proposed an additional function: 
a) Available for active events, 
b) Whose purpose is to record who and when the active event was assignee, 
c) Behaves like a acknowledged, i.e. such an assignee event is not taken into account in the calculation highest alarm, but it does not disappear from the list of Pending events, so here it works similarly to silenced, with the difference that it is visible to all users; (Combination of acknowledged and silenced functions)
d) This can be done by one user and this assignment cannot be changed; 
e) If the event receives the "Return to normal" status, ackonoledged appears instead of this function. Similarly, if the event has the status "No RTN".

Assign(user plus) and Assignee(user minus) for Urgent event
![image](https://github.com/SCADA-LTS/Scada-LTS/assets/35842300/c63730c6-9168-4c8d-8549-f4b815c511fa)

![image](https://github.com/SCADA-LTS/Scada-LTS/assets/35842300/5393f5eb-4eef-44e2-a94c-c1f97ecbc90f)

![image](https://github.com/SCADA-LTS/Scada-LTS/assets/35842300/a9a7bb31-7bb5-42c4-b50b-9447f4a63d4b)

Edit:
1. Each user can assign an unassigned event to himself; 
2. Just as he can assign it to himself, he can withdraw it and unassign the event, he cannot do it for another user unless he is an admin. 
3. User assignment has the effect that this event is not taken into account when calculating the highest alarm, but is still visible in the Alarms, pending events tab;
4. After assignment, the Assignee column displays the assignment date and username of the assigned user; 
5. Other users visible this attribution; 
6. Only one user can be assigned to an event; 
7. In Event search, in the status field, you can select Assignee and search for events with assignment; 
8. An option has been added to disable this function, which has the effect that the buttons in the column for the assignment function are invisible, it can be turned on and off in System Settings; 
9. You can make the assignment in 4 places: 
- in the Alarms tab;
- on the WatchLists tab for events associated with the point;
- on the WatchLists tab on the 'Loupe' button;
- on the Graphical Views tab in the view on the 'Alarm List' component;
10. Assigning and unassigning a user from an event generates an event about that event;
11. Possibility to enable and disable this function in System Settings;
12. Disabling this feature resets the value in the Assignee column in the Events table for active events, which has the effect of being taken into account for the highest alarm calculation;

*Specifications*
Scada-LTS Version: 2.6.18

**Comment by Limraj** [comment]
Hi @GabrielTec251,
Will this be ok?

**Comment by GabrielTec251** [comment]
In version 2.7.5.4 I have a server script that works as follows:

creates an alarm table so that the alarms only disappear when it is recognized and is inactive.

however, this is only in the graphical visualization, not on the standard scada alarms page,

however, for the client, I only provide the graphical visualization, so in it I create an alarm screen and create this table that even shows whether the alarm was recognized or not,


and when it goes to the report it behaves like in previous versions

![aaa](https://github.com/SCADA-LTS/Scada-LTS/assets/138117880/5d360d54-8730-4419-b05d-1ba3919eed1c)

**Comment by GabrielTec251** [comment]
I believe that the best solution would be to leave the alarm behavior as in the previous version and I could implement this script on the alarm page, or just follow the same logic as it.

**Comment by GabrielTec251** [comment]
it is in Portuguese, 1st column informs the alarm level;

2nd informs the time the alarm was activated;

3rd column informs the message

4th informs whether the alarm is active or inactive

5th informs if it has been recognized or is pending

6th informs the alarms

**Comment by GabrielTec251** [comment]
I imagine that putting the old version version <2.7.5.4 and putting a condition so that instead of the alarm disappearing from the alarm list only when it is recognized, you could put another condition that would be "not active" which would be an easier solution that meets greater demand from users, helps with operation control and provides a cleaner report;

But it's just speculation, I don't really know the complexity of developing something like this

**Comment by Limraj** [comment]
@GabrielTec251 I'm trying to step in and do what you need, even though you don't pay me anything for it. I have already explained that this results from the arrangements with our client, so the acknowledged action will not change. The rest works as in previous versions. If this doesn't suit you, you can use older versions and everyone will be happy.

**Comment by GabrielTec251** [comment]
I'm sorry if I sound rude, that's not my intention, I was just trying to show the point of view of how we use this function, obviously it's not something that impacts the application, and as I said I don't know the real difficulty of doing it once that I am not from the area;

In any case, this suggestion you gave will be of great help and can be worked on efficiently;

I thank you in advance and I apologize if I sounded in any way uncomfortable, it really wasn't my intention, I don't know if it's a translation error, in any case, I'm sorry

**Comment by GabrielTec251** [comment]
In fact, some words are not well translated and change the connotation of what I said a little

**Comment by GabrielTec251** [comment]
> Oi@GabrielTec251, Isso vai ficar bem?
yes it stays

**Comment by Limraj** [comment]
@GabrielTec251 
If someone doesn't want to cooperate, you can't force them, no matter what you do, nothing will come of it. There's nothing more I can do. Take care.

**Comment by GabrielTec251** [comment]
As I said, I'm sorry, it wasn't my intention; If there is any way I can contribute, I would be grateful.

**Comment by GabrielTec251** [comment]
I'm looking for a way to show how sorry I am for this inconvenience;

and I was also informed that I made some mistakes in your semantics;

for example, here we don't use "I would like" before asking for something, and that may have sounded negative;

we usually say "I want"

Maybe for linguistic or cultural reasons some of the things I said sounded really bad, but I swear I was just trying to contribute;

Once again, I am very sorry for the inconvenience

**Comment by Limraj** [comment]
@GabrielTec251 
I only explained the situation, why the action in the pending list has changed, and since I can't go back to the previous 'acknoledged' behavior, I proposed other solution. As I say, if what I propose is not satisfactory enough that nothing can be done about it, then it is not necessary for us to continue with it. My attitude is only that I try to help when someone has a problem and that's all, I don't force anyone to cooperate, especially if what I can do is not useful.

**Comment by GabrielTec251** [comment]
What you proposed is useful, yes, I didn't understand it at first, when I came to understand the conversation had already unfolded, it was my mistake, you just tried to help

**Comment by GabrielTec251** [comment]
@Limraj

Could you forgive me for my mistake?

I am very grateful for your work

This solution is perfect, now that I understand it will be of great help


f it is still possible, I would like you to accept my apology and implement your solution;

or at least accept the apology, it is of great personal importance to me

**Comment by Limraj** [comment]
@GabrielTec251 I don't fully understand your reaction, I just wanted to know if we can help with your problem, I don't feel offended etc. The only problem I had was that in my opinion you were not interested in reaching an agreement, although maybe translation, but I guess that's also it is no longer relevant, as far as I am concerned, I do not feel offended, insulted, etc. in any sense.

**Comment by GabrielTec251** [comment]
he solution you propose at the beginning is perfect

; Could you implement it please?

Note: The translation changes the tone of what is said a lot, I thought I offended you and I'm relieved I didn't do that

note 2: I'm going to take an English course to improve this

**Comment by Limraj** [comment]
@GabrielTec251 
We are discussing it in the team... I will let you know what the result is.
