### ISSUE TITLE
HTTP settings and proxy usage

### ISSUE THREAD

**Issue by weschenfelder** [SCADA-LTS/Scada-LTS#2751]
Hello @Limraj , during a conversation, we came to some specific doubts about the use of this functionality, could you clarify what its real usefulness is?

I think it would be used to communicate between different Points of Scada-LTS, but I didn't find anything in forums or support materials about its use.

![image](https://github.com/SCADA-LTS/Scada-LTS/assets/82856001/af3357eb-bca1-4712-86e3-b1e253f65024)

![image](https://github.com/SCADA-LTS/Scada-LTS/assets/82856001/02787509-1d51-4753-b617-e01b81bf24dc)
expected functionality diagram.

**Comment by Limraj** [comment]
Hi @weschenfelder,
you can configure a server/http proxy and use it with our application.

If your question is not about an error or application improvement, please post it [here](https://github.com/SCADA-LTS/Scada-LTS/discussions). You can count on the community with such questions, they use scada more than us.

Regards,
Kamil Jarmusik
