### ISSUE TITLE
Selection of binary graphic : no visualisation of what has been selected

### ISSUE THREAD

**Issue by nduvernois** [SCADA-LTS/Scada-LTS#2774]
In graphical view, during the configuration of a binary graphic, you can't see what has been selected for choices 0 & 1.
Expected behaviour is the same as in ScadaBR, i.e. the selected symbol is squared, but it could be highlighted, underlined, or whatever other visible mark.

ScadaLTS 2.6.18

**Comment by fabiodurao** [comment]
It has already been fixed in version 2.7.6

https://github.com/SCADA-LTS/Scada-LTS/issues/2520
