### ISSUE TITLE
Cannot install ScadaLTS

### ISSUE THREAD

**Issue by nex2000** [SCADA-LTS/Scada-LTS#2786]
sorry if I write here but no one responds in the linux installer.

I would like to know why the installer works very well on first launch. On the second start ScadaLTS goes to stop and I get this error.
I followed the installation guide step by step everything worked but after shutting down and restarting I get this error

***********

Caused by: java.net.ConnectException: Connessione rifiutata (Connection refused)

3-Nov-2023 19:34:57.446 AVVERTENZA [main] org.apache.catalina.core.NamingContextListener.addResource Failed to register in JMX: [javax.naming.NamingExceptio>

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.]]
23-Nov-2023 19:34:58.021 INFORMAZIONI [main] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enabl>
23-Nov-2023 19:35:00.483 AVVERTENZA [main] org.apache.tomcat.jdbc.pool.ConnectionPool.checkPoolConfiguration maxIdle is larger than maxActive, setting maxIdl>
23-Nov-2023 19:35:00.499 GRAVE [main] org.apache.tomcat.jdbc.pool.ConnectionPool.init Unable to create initial connections of pool.
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.

**Comment by fabiodurao** [comment]
The installation script does not yet configure Scada-LTS startup automatically along with the OS. After starting the OS, you will need to run the same scripts in the same order, mysql -> tomcat, this time nothing will be installed, it will just start the process, after that you can open the browser and access Scada-LTS.

**Comment by Limraj** [comment]
Hi @fabiodurao and @nex2000,
"The installation script does not yet configure Scada-LTS startup automatically along with the OS. "
We are not planning a change in this direction... 

@nex2000 You have the answer in: https://github.com/SCADA-LTS/linux-installer/issues/4
If this solves the problem, you can close both topics.

**Comment by nex2000** [comment]
Hello I solve the trouble with restart the service

Thanks a lot Fabio & Limraj

Paul
