### ISSUE TITLE
Typo in the project description (Acquisiton → Acquisition): needs an admin to fix it

### ISSUE THREAD

**Issue by Coeur** [SCADA-LTS/Scada-LTS#2789]
**Describe the bug**
Typo in the project description (Acquisiton → Acquisition): needs an admin to fix it.

**To Reproduce**
1. Go to https://github.com/SCADA-LTS/Scada-LTS
2. See typo

**Expected behavior**
Spelling "**Acquisition**" (instead of "Acquisiton")

**Screenshots**
<img width="1236" alt="Screenshot 2023-12-04 at 23 45 34" src="https://github.com/SCADA-LTS/Scada-LTS/assets/839992/f8bea2d9-a31c-4dfd-a6cd-d1cfbd802539">

**Desktop (please complete the following information):**
 - OS: All
 - Browser: All
 - Version: All

**Additional context**
Issue reported 4 years ago on #1067.

**Comment by Limraj** [comment]
Hi @Coeur,

Thank you for reporting this, this typo certainly didn't look very professional.
It has been corrected, if it is ok, you can close this issue.

Regards,
Kamil Jarmusik
