### ISSUE TITLE
Missing "alt" to button

### ISSUE THREAD

**Issue by RenatoExpert** [SCADA-LTS/Scada-LTS#2790]
**Describe the bug**
Missing html property alt for "new point" button

**To Reproduce**
1. Go to '/Scada-LTS/data_source_edit.shtm?dsid=1#/alarms/scada' - edit one data source
2. Scroll down to 'Points'
3. See there is no message

**Expected behavior**
It should display a description

**Screenshots**
New point button (no description)
![Screen Shot 2023-12-05 at 10 38 56](https://github.com/SCADA-LTS/Scada-LTS/assets/20760510/c36e02c3-d9be-4912-ba69-cef13127da98)

An example of its neighboor button
![Screen Shot 2023-12-05 at 10 42 22](https://github.com/SCADA-LTS/Scada-LTS/assets/20760510/74497b71-1a1c-4236-bf95-0a1e0f2938dd)

**Desktop (please complete the following information):**
 - OS: Linux Docker (backend) - MacOs (frontend)
 - Browser Chrome
 - Version v2.7.6.1 (4bc25b7)

**Comment by Limraj** [comment]
Hi @RenatoExpert,
Programmer @ga7x is correct in https://github.com/SCADA-LTS/Scada-LTS/issues/2723 (pr https://github.com/SCADA-LTS/Scada-LTS/pull/2739), will come in version 2.7.7.

Regards,
Kamil Jarmusik
