### ISSUE TITLE
Upgrade Node

### ISSUE THREAD

**Issue by Limraj** [SCADA-LTS/Scada-LTS#2805]
**Target**
- replacement of js libraries/versions with deprecated status by currently supported versions;
- eliminating vulnerabilities;

**Solution**
- [x] upgrade Node LTS version (min 20, nice 22, best 24);
- [x] upgrade versions for other js library (to the minimum version on which the build works);
- [x] updating supported node versions in the wiki:
https://github.com/SCADA-LTS/Scada-LTS/wiki/Getting-started-Development-%E2%80%90-Linux
https://github.com/SCADA-LTS/Scada-LTS/wiki/Getting-started-Development-%E2%80%90-Windows

**Links**
[Node archive](https://nodejs.org/en/about/previous-releases)
[Upgrade to node 14 - example](https://github.com/SCADA-LTS/Scada-LTS/pull/2366/files)

**Additional context**
Scada-LTS version: 2.7.6.1

**Comment by YuaFox** [comment]
Cypress was using an old ssl protocol, I updated it using the migration tool to the latest version.

After upgrading nodejs it would be nice to migrate vue 2.7 to vue3 and remove some dependences.

For example Scada-LTS uses vuetify.

vue-color-picker-wheel: we can use https://vuetifyjs.com/en/components/color-pickers/#usage
vuejs-datepicker: we can use https://vuetifyjs.com/en/components/date-pickers/#usage

**Comment by Limraj** [comment]
Hi @YuaFox,
The purpose of this task is to make the min that are necessary for the project to be built and work on new version Node (node is only used for frontend compilation, but you need to check if this compilation works).
We tend not to remove dependencies, unless you can prove that it is not used by sources and other libraries, but I would suggest doing this in a separate issue.

Regards,
Kamil Jarmusik
