### ISSUE TITLE
Time zone selection

### ISSUE THREAD

**Issue by nvlong248** [SCADA-LTS/Scada-LTS#2807]
Can we select time zone? I see the program fix UTC-8 time zone.

**Comment by Limraj** [comment]
Hi @nvlong248,
1. Have you used our app installers?
https://github.com/SCADA-LTS/linux-installer
https://github.com/SCADA-LTS/windows-installer

2. What system are you running the application on?

3. Generally, we can change the time zone in tomcat, so this change affects the server, not the client. This means you can set one time zone for all application users, e.g. if they are in a different time zone, the displayed time will be consistent with what you have set in tomcat.
You also need to find the time zone id to set this time offset relative to UTC:
https://www.ibm.com/docs/en/was-nd/8.5.5?topic=ctzs-time-zone-ids-that-can-be-specified-usertimezone-property

[timezone_all_ids.txt](https://github.com/SCADA-LTS/Scada-LTS/files/13975518/timezone_all_ids.txt)

If you have any more questions on how to set this in tomcat, let me know. It depends on what system you are running on and whether you have used our installers.

edit:
In addition to tomcat, it may turn out that this is also necessary for the mysql server. E.g. if the NOW() function is used.

edit2:
And also if the Date.now() function is used in javascript, it is from the client side.

Currently, there may be a problem with the operation of applications where the time zone of the server and client is different. 

This is a topic for consideration in our team.

Regards,
Kamil Jarmusik

**Comment by nvlong248** [comment]
Hi Kamil,
Thanks for your reply.
I am running the application on Windows 10 PC.
It's necessary to set the time zone following the time zone set on PC. Can
you give an instruction how to change it?

Kind regards,
Long
