### ISSUE TITLE
Modbus point read illegal data value

### ISSUE THREAD

**Issue by nvlong248** [SCADA-LTS/Scada-LTS#2813]
Modbus Point locator test returns "Illegal data value" notice while the same register can be read at Modbus read data feature.

![image](https://github.com/SCADA-LTS/Scada-LTS/assets/156666839/9d179cf6-d777-4d79-a953-15790b46e012)

**Comment by Limraj** [comment]
Hi @nvlong248,

Does it work with another type?

Regards,
Kamil Jarmusik

**Comment by nvlong248** [comment]
Hi @Limraj 
Depends on some registers, it can work with 4 byte integer or 8 byte integer. But it would be helpful if I can add single register as 2 byte integer.
Regards,
Long

**Comment by Limraj** [comment]
Hi @nvlong248,
from what I see, these values ​​are 4 bytes, so if we try to read them as 2 bytes, do we have an error? Or maybe I got something wrong? Because if I'm right, this is correct behavior...

Regards,
Kamil Jarmusik

**Comment by Patrykb0802** [comment]
Hi @nvlong248,

I looked into this issue however I could not reproduce your error. Below are screenshots of my Scada configuration on different versions: 

version 2.6.18:
![image](https://github.com/SCADA-LTS/Scada-LTS/assets/56111976/cf2583d3-49d7-44fc-bd5e-c2c81a36b52e)

version 2.7.7.3:
![image](https://github.com/SCADA-LTS/Scada-LTS/assets/56111976/347d75c8-ae60-4e82-8295-c0ee14a9b989)


### What version of Scada-LTS application are you using ?
### Could you send screenshot of returned values from Modbus while using Modbus data type 4 or 8 byte unsigned integer on the same configuration ?

Regards,
@Patrykb0802

**Comment by Patrykb0802** [comment]
We tried to reproduce this error, but with no results, if the problem occurs again, please contact us.

Regards,
Scada-LTS development team
