### ISSUE TITLE
Update Point Properties Examples

### ISSUE THREAD

**Issue by odenisnobre** [SCADA-LTS/Scada-LTS#2815]
I'm trying to use the /point_properties/updateProperties endpoint
but it is giving error 400.
I'm passing the cookies in the request and the object in the message:
{"enabled": false}
url: http://192.168.1.82:8088/Scada-LTS/api/point_properties/updateProperties?id=101

My need is to be able to enable or disable a data point via API in order to control when data is collected.

Version: 2.7.6
Platform: Linux
Subsystem: Docker

**Comment by Limraj** [comment]
Hi @odenisnobre,
You should have a message in response why you are getting 400.

Regards,
Kamil Jarmusik

**Comment by odenisnobre** [comment]
Hi @Limraj 
How to use Node-RED are the settings I am using as the message body (on the left) and the request return (right side)

![image](https://github.com/SCADA-LTS/Scada-LTS/assets/8119694/39ecf4a2-7414-4dd2-af43-e280c3f0a071)

**Comment by Limraj** [comment]
Hi @odenisnobre,
https://nodered.org/docs/user-guide/messages
try for response:
`msg.payload`

From what I see, this endpoint is not correct, to enable or disable Data Point, you would need to use endpoint:
PATCH (no POST, no PUT) /api/point_properties/{id}/toggle

With the caveat that if the point is currently turned on, calling this endpoint turns the point off, if it is turned off, it turns the point on.

Regards,
Kamil Jarmusik

**Comment by odenisnobre** [comment]
Well, using the endpoint you provided, the toggle worked and worked as needed, even if done using Python and not Node-RED for now because PATCH is not found in the current library.

This way it works perfectly.
Now would you be able to get the current status of the tag to know if the toggle will be enabled or disabled?

**Comment by Limraj** [comment]
In the response of this endpoint, there is information whether the endpoint has been enabled or disabled.

In version 2.7.7 we will add two additional PUT endpoints:

/api/datapoint/enabled?id=point_id(or xid=point_xid)
/api/datapoint/disabled?id=point_id(or xid=point_xid)

**Comment by odenisnobre** [comment]
I understood.
These new endpoints will be interesting for the new version.

Regarding the response to the /toggle request, the status actually came, enable=true/false
But it would be interesting to have visibility of the current status to know if I am enabling or disabling, because only the command and the response to the last command may not work.

**Comment by Limraj** [comment]
Try:
GET /api/datapoint?id=point_id

**Comment by odenisnobre** [comment]
Perfect.
It works this way.

Thank you very much and this topic can be closed.

**Comment by odenisnobre** [comment]
All doubts were answered.
Thanks.
