### ISSUE TITLE
Windows installer v2.0.1 for ScadaLTS 2.7.7.3 not working properly

### ISSUE THREAD

**Issue by eng-rodrigo-lobo** [SCADA-LTS/Scada-LTS#2900]
**Describe the bug**
I tried to install the new version of ScadaLTS 2.7.7.3 but after the installation process I can't access the Scada UI.
I get a screen with the following text:

System exception!

The server has experienced an exception processing your last request. The exception has been logged, and system administrators will be notified of this problem. You may continue to use the site. We apologize for the inconvenience.

Please provide the following code to the administrator to identify the problem:
20240527182954591

**To Reproduce**
1. Open the Windows Installer v2.0.1
2. Proceed with the installation
3. Try to open ScadaLTS for the fisrt time after the instalation is completed

**Expected behavior**
I expected to access the ScadaLTS UI to program the system, add datasources, etc

**Screenshots**
![image](https://github.com/SCADA-LTS/Scada-LTS/assets/30940001/a1115f2b-53ed-400c-9abd-3896a11c82cf)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Microsoft Edge
 - Version: 125.0.2535.67

**Additional context**
Tomcat seems to be running fine. I can access the server, start and stop, no big deal. I noticed that no tables were created after the installation. I dumped a bkp after the installation, so the expected tables would be available, but the problem still persists.

I checked the logs and it looks it's getting some trouble when starting the services, but it's too advanced for my knowledge... I can provide them if necessary.

[scada-lts-stdout.2024-05-27.log](https://github.com/SCADA-LTS/Scada-LTS/files/15461975/scada-lts-stdout.2024-05-27.log)
[catalina.2024-05-27.log](https://github.com/SCADA-LTS/Scada-LTS/files/15461977/catalina.2024-05-27.log)
[commons-daemon.2024-05-27.log](https://github.com/SCADA-LTS/Scada-LTS/files/15461978/commons-daemon.2024-05-27.log)
[localhost.2024-05-27.log](https://github.com/SCADA-LTS/Scada-LTS/files/15461979/localhost.2024-05-27.log)
[localhost_access_log.2024-05-27.txt](https://github.com/SCADA-LTS/Scada-LTS/files/15461980/localhost_access_log.2024-05-27.txt)
[scada-lts-stderr.2024-05-27.log](https://github.com/SCADA-LTS/Scada-LTS/files/15461981/scada-lts-stderr.2024-05-27.log)

**Comment by Limraj** [comment]
Hi @eng-rodrigo-lobo,
1. Try stop tomcat and start again;

2. Open cmd and execute:
`echo '%CATALINA_HOME%' `
Is the installation path set here? (It should be: 'D:\Scada-LTS\tomcat')
If this is not the case, set the following environment variable:
`set CATALINA_HOME='D:\Scada-LTS\tomcat'`

3. Have you installed a different version of Scada-LTS on this system?

4. If this doesn't work, uninstall Scada-LTS and run as administrator. **If you had a database, remember to make a backup before uninstalling the application, because it will be deleted.**

edit:
try **Set Environment Variable in Windows via GUI** (set CATALINA_HOME)
https://phoenixnap.com/kb/windows-set-environment-variable
and restart tomcat

Regards,
Kamil Jarmusik

**Comment by eng-rodrigo-lobo** [comment]
Hey @Limraj !

I tried your suggestions and now it's working fine!

To be honest I'm not sure what was the actual problem, but I suspect it's related to the environmento variable, because after I created it the application started working fine. I ran the installer as admin as well, so maybe both conditions were necessary also, but I can't say for sure.

I had another version of ScadaLTS installed before (2.7.6) but I uninstalled it to upgrade to the new version, so when I was installing v 2.7.7.3 there was no SLTS installed.

Is it possible to embed this procedure (set env variable) into the installer? So we don't have to do it manualy every time we install the program.

**Comment by Limraj** [comment]
Corrected installator: https://github.com/SCADA-LTS/windows-installer/releases/tag/v2.0.2

**Comment by Kaushik0o7** [comment]
is the graphical views disabled in SLTS v.2.7.8 ? what are supposed to replace it with ?

**Comment by Limraj** [comment]
Hi @Kaushik0o7,
Can you provide more details? (screens, a more detailed description of how to reproduce the problem)

We have Graphical Views disabled but only on the new UI. Everything should work on the old UI.

Regards,
Kamil Jarmusik
