### ISSUE TITLE
Add a docker arm64 image

### ISSUE THREAD

**Issue by YuaFox** [SCADA-LTS/Scada-LTS#2901]
Currently Scada-LTS does not offer a docker image for arm64, making it impossible to run on the Raspberry Pi board or on arm64 desktop/servers.

While you can run it doing a manual install, being able to run it on rpi with just the docker-compose would be handy.

edit:
*Linked*
#2904
#460

**Comment by Limraj** [comment]
Hi @YuaFox,
We will consider deploying this version of the docker image, but for now you can use our linux installer: https://github.com/SCADA-LTS/linux-installer

If you know Docker and can give us some advice on this topic, we'd love to hear it.

Regards,
Kamil Jarmusik

**Comment by YuaFox** [comment]
Hi @Limraj 

I created this pull request with the changes (including github actions) to create the arm64 version. Feel free to provide feedback/additional modifications required.

https://github.com/SCADA-LTS/Scada-LTS/pull/2902
