### ISSUE TITLE
[Feature] Support for ARM64 devices?

### ISSUE THREAD

**Issue by Rafael-OliveiraBR** [SCADA-LTS/Scada-LTS#2904]
**Is your feature request related to a problem? Please describe.**
I tried to install it in an Orange Pi 3B+ through the docker-compose file available on the docker tutorial, it throws an error when trying to start scadaLTS.

![image](https://github.com/SCADA-LTS/Scada-LTS/assets/18638490/700f2827-2dfd-43c0-b48f-38bd69640e2b)

Looking at the tags on the docker hub I realized it's only available for amd64 architecture, no aarch64 support.

**Describe the solution you'd like**

It would be nice if it supports ARM64 architecture as well.

**Comment by Limraj** [comment]
Hi @Rafael-OliveiraBR,
If you know Docker, we'd love to hear your advice. 
For now, it's worth trying our linux installer:
https://github.com/SCADA-LTS/linux-installer

Regards,
Kamil Jarmusik
