### ISSUE TITLE
Project export error ERR_INVALID_RESPONSE

### ISSUE THREAD

**Issue by neuchengon** [SCADA-LTS/Scada-LTS#2942]
**Describe the bug**
When I tried to donwload the project file into ZIP, a new web page open but shows error, see the screenshot. 

This site can’t be reachedThe web page at http://192.168.6.28:8090/ScadaBR/export_project.htm?projectName=ScadaBR%201.2&includePointValues=true&includeUploadsFolder=true&includeGraphicsFolder=false&projectDescription=213&pointValuesMaxZip=100 might be temporarily down or it may have moved permanently to a new web address.
ERR_INVALID_RESPONSE

**To Reproduce**
1. Go to 'import/export' icon from the top tool bar.
2. Click on 'Export Project'
3. See error "File not found". 
4. I tried Chrome and Firefox browser, either does not work. 

**Expected behavior**
I expected the page can open and download the project file in ZIP format. 

**Screenshots**
![image](https://github.com/SCADA-LTS/Scada-LTS/assets/153329380/d2a24e98-b064-4bce-b92f-138cd0c622b5)

![image](https://github.com/SCADA-LTS/Scada-LTS/assets/153329380/bcaf409b-a321-4efa-bcc7-8a542257765e)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome/Firefox
 - Version Firefox 127.0.2 (64-bit), Chrome Version 126.0.6478.127 (Official Build) (64-bit)

**Comment by Limraj** [comment]
Hi @neuchengon,
From what I see you are using ScadaBR, our team is developing Scada-LTS. 

So we don't know exactly what's going on, but maybe it's a permissions problem(on server, permission for process tomcat with ScadaBR), maybe the export function can't create a temporary file on the server that is necessary for this function to work properly. I think it's worth checking before taking any other steps.

We encourage you to migrate to Scaca-LTS (on server):
**1. First backup your database;**
2. Install Scada-LTS stable version v2.6.18 or prerelease version v2.7.7.3 (modern version);
- Stopped ScadaBR;
- If installed ScadaBR or other process on port 8080, then change on free port; (e.g. 8082)
- If use external database, then uncheck 'Install local sever' on winodws-installer, or not execute bash script mysql_start.sh on linux-installer, and set data to accsess to MySQL database server;
- **Use linux-installer:**
[Installation help](https://github.com/SCADA-LTS/linux-installer?tab=readme-ov-file#installer-scada-lts-for-linux)
Download installer:
https://github.com/SCADA-LTS/linux-installer/releases/tag/v1.4.2
- **Use windows-installer:**
[Installation help](https://github.com/SCADA-LTS/windows-installer?tab=readme-ov-file#table-of-content)
Download installer:
https://github.com/SCADA-LTS/windows-installer/releases/tag/v2.0.3

3. Other configuration: (optional)
[Configuration-redirect-ScadaBR-to-Scada-LTS](https://github.com/SCADA-LTS/Scada-LTS/wiki/Configuration-redirect-ScadaBR-to-Scada%E2%80%90LTS-%5BTomcat-9.0-Linux-Windows%5D)


Kind regards,
Kamil Jarmusik
