### ISSUE TITLE
System exception!

### ISSUE THREAD

**Issue by luwz** [SCADA-LTS/Scada-LTS#2993]
System exception!

The server has experienced an exception processing your last request. The exception has been logged, and system administrators will be notified of this problem. You may continue to use the site. We apologize for the inconvenience.

Please provide the following code to the administrator to identify the problem:
20240826100839165

**Comment by Limraj** [comment]
Hi @luwz,
If you do not describe the circumstances of the error, we will not be able to do anything:
1. What operating system are you using?
2. What version of the application/branch are you using?
3. What steps did you take to build your war?
4. Have you followed the instructions in the manual?
[Getting-started-Development-Linux](https://github.com/SCADA-LTS/Scada-LTS/wiki/Getting-started-Development-%E2%80%90-Linux)
[Getting-started-Development-Windows](https://github.com/SCADA-LTS/Scada-LTS/wiki/Getting-started-Development-%E2%80%90-Windows)
5. Send logs from tomcat/Intellija;
6. The most common cause of problems at the beginning are problems with connecting to the database, you need to check whether you have installed and started the database server, or you can also use our installer:
[windows-installer](https://github.com/SCADA-LTS/windows-installer)
[linux-installer](https://github.com/SCADA-LTS/linux-installer)

Regards,
Kamil Jarmusik

**Comment by Limraj** [comment]
Hi @luwz,
We invite you to ask questions and solve problems with environment configuration here:
https://github.com/SCADA-LTS/Scada-LTS/discussions

Regards,
Kamil Jarmusik
