### ISSUE TITLE
Problem with configuring the development environment with Intellij

### ISSUE THREAD

**Issue by luwz** [SCADA-LTS/Scada-LTS#2994]
May I ask why I can use the official Scada LTS.war image package, but when I use IDEA to create my own Scada LTS.war package locally, it doesn't work properly?

**Comment by Limraj** [comment]
Hi @luwz,
you haven't written anything that could lead us to the cause of your problems. 
Try to install the environment according to the instructions:
https://github.com/SCADA-LTS/Scada-LTS/wiki/Getting-started-Development-%E2%80%90-Windows
https://github.com/SCADA-LTS/Scada-LTS/wiki/Getting-started-Development-%E2%80%90-Linux

I corrected the title of the issue, we don't create such long titles. We try to keep them short but include the most important keywords for the problem.

If you have questions you can use:
https://github.com/SCADA-LTS/Scada-LTS/discussions

Regards,
Kamil Jarmusik

**Comment by Limraj** [comment]
Hi @luwz,
We invite you to ask questions and solve problems with environment configuration here:
https://github.com/SCADA-LTS/Scada-LTS/discussions

Regards,
Kamil Jarmusik
