### ISSUE TITLE
Editing empty graphic views

### ISSUE THREAD

**Issue by Morzyniec** [SCADA-LTS/Scada-LTS#301]
#287 Refers to point 1 in the scenario.
Open empty page "Graphic views". After clicking on the button "edit view" appears information:
"System exception!
The server has experienced an exception processing your last request. The exception has been logged, and system administrators will be notified of this problem. You may continue to use the site. We apologize for the inconvenience."

**Comment by Limraj** [comment]
Empty Graphical View can be edited, error does not appear.
