### ISSUE TITLE
Alarm List widget not working 

### ISSUE THREAD

**Issue by nex2000** [SCADA-LTS/Scada-LTS#3012]
Hello

I inserted the Alarm list component into a graphic page, even though there are alarms, it does not signal anything.
The release is 2.7.8

![image](https://github.com/user-attachments/assets/0e7262b5-161a-4908-9cab-b9dd69adc149)

![image](https://github.com/user-attachments/assets/b386d56d-32b6-4e4e-beac-91e7c258d496)

Regards

**Comment by nex2000** [comment]
it worked now but i had to restart the server

Regards

**Comment by Limraj** [comment]
Hi @nex2000,
We cannot reproduce this, perhaps a more restrictive alert level was saved and then changed in select but this change was not saved using the "Save" button. 
Another possible cause is that the UI Performance parameter in System Settings is set to too long a period, which means that the table was not filled with events for some time.

Regards,
Kamil Jarmusik
