### ISSUE TITLE
Working with MQTT milliseconds and display interface

### ISSUE THREAD

**Issue by Silonei-Duarte** [SCADA-LTS/Scada-LTS#3029]
Good afternoon, dear all, I'm new here, and I'm from Brazil.

I've been developing an interface to capture MQTT data in SCADA_LTS, which is updated in milliseconds, since they are critical sensors.

However, the interface, both in the configuration and in the Datapoints display, only displays seconds. I realized that it is possible to collect data in milliseconds by adding a 0 in front, 0500 seconds,
although the interface then changes to 500 seconds, the data is still collected with reference to 0500

However, the interface in general still only displays in seconds; I understand that it goes beyond a configuration file. Can you tell me where to start to implement this change or if there are any plans to add milliseconds to the code in future native versions.

**Comment by Limraj** [comment]
Hi @Patrykb0802,
Please note that the issue number is **3029** and not 3028.

@Silonei-Duarte, Thank you for pointing out this limitation.
edit:
I understand that you would be interested in setting 500 ms? Please note that this setting should not be too low, so as not to overload the database with records.

Regards,
Kamil Jarmusik

**Comment by Silonei-Duarte** [comment]
Good afternoon Limraj;
Thank you very much for your feedback and attention.
In my case, the normal time would be 200 milliseconds, currently this is the time we have running on the terminals to generate data, I set it to 500 milliseconds because it is the maximum limit I can work with.
Hardware would not be our problem and data retention will not be too long so as not to overload the database and writing.
I tested it with 0200 seconds and we were able to work in these scenarios, the system can capture and display it, you did a great job in optimizing it, but I understand that I am "messing around", because natively the data is displayed in whole seconds.

**Comment by Limraj** [comment]
Hi @Silonei-Duarte,
I'm sorry at the beginning, the Update parameter in this Data Source is related to something other than the frequency of writing values ​​to the database(for change value on Data Point and default Logging properties -> 'When point value changes'), I haven't checked it before.

The Update parameter for this Data Source means the period during which the connection for the Data Source is checked and repeated, if necessary.

This will be saved (for int type 0200=200), but the Data Source connection (connection refresh) will be checked within a period of 200 seconds. 

However, this Data Source is designed in such a way that if there is a change in the value on the subscribed topic, it immediately updates the value for the points, regardless of the Update parameter, so you can observe that it works as you expect.

edit:
**Do you expect that the Update parameter, which determines connection checking and retrying, could be configured in milliseconds?**

Regards,
Kamil Jarmusik

**Comment by Limraj** [comment]
Hi @Silonei-Duarte,
1. Let me know if the description of the MQTT Data Source operation, and specifically the Update parameter, is clearly explained by me?
2. Do you expect to be able to set this parameter (Update) in milliseconds?

I hope I understood you correctly. 

Regards,
Kamil Jarmusik
