### ISSUE TITLE
report created from watch list "blabla" is named "Copy of blabla"

### ISSUE THREAD

**Issue by nduvernois** [SCADA-LTS/Scada-LTS#3031]
Create a watch list ("blabla") with a few datapoints and click on "create report for this watchlist". The report view is the opened and, by default, the new report is named "copy of blabla". 

The naming makes little sense to me in this situation. If a watch list is copied to a new watch list, it makes sense to name it "copy of blabla". But in this situation, a new report is created and, as long as no existing report uses the same name, I see no point in naming it "copy of ..."

Proposed solution : just use the name of the watchlist without any change

OS : Windows Server 2016
Browser : Chrome 129
ScadaLTS version : v2.7.7.3_For build 3789793776

**Comment by Limraj** [comment]
Hi @nduvernois,
we assumed, we will probably fix it in the next version 2.8.0.

Regards,
Kamil Jarmusik
