### ISSUE TITLE
point name in point properties page has a limited visible length

### ISSUE THREAD

**Issue by nduvernois** [SCADA-LTS/Scada-LTS#3036]
I have a data source called "B533 - salle 101", which contains quite a few datapoint such as this one : "B'PoOs'RPO_101'RHvacCoo'TCtlC'PrSpCCmf Csg froid confort" (56 characters)
The first part of this name "B'PoOs'RPO_101'RHvacCoo'TCtlC'PrSpCCmf" is nothing else but the real name matching Siemens naming convention. The second part is a comment to make the name more understandable.

In the "data source" field (top left), the data source name is fully visible
In the "point name" field (top left), I can see only the first 23 characters, so "B'PoOs'RPO_101'RHvacCoo"
In the "goto" field (top right), I can read "B533 - salle 101 - B'PoOs'RPO_101'RHvacCoo'TCtlC'PrSpCCmf Csg froi", but the full name is visible when I click on it

It's fine to have the "goto" field slightly truncated, as far as the full name is visible in the "point name" field, which is not the case.

OS: Windows Server 2016
Browser : Chrome 130
Version : v2.7.7.3_For build 3789793776

**Comment by Limraj** [comment]
Hi @nduvernois,
can you send screenshots?

Regards,
Kamil Jarmusik
