### ISSUE TITLE
Scada-LTS support MQTT or not?

### ISSUE THREAD

**Issue by Pencexiang** [SCADA-LTS/Scada-LTS#3070]
Scada-LTS support MQTT or not?

**Comment by Limraj** [comment]
Hi @Pencexiang,
we support MQTT.

It's best to ask such questions here:
https://github.com/SCADA-LTS/Scada-LTS/discussions

Regards,
Kamil Jarmusik

**Comment by Pencexiang** [comment]
OK,Thx

**Comment by Pencexiang** [comment]
> Hi @Pencexiang, we support MQTT.
> 
> It's best to ask such questions here: https://github.com/SCADA-LTS/Scada-LTS/discussions
> 
> Regards, Kamil Jarmusik

OK,Thx
