### ISSUE TITLE
ScadaLTS REST API JSON Data

### ISSUE THREAD

**Issue by radek2s** [SCADA-LTS/Scada-LTS#342]
This issue applies to the REST API with Alphanumeric DataPoints.

To send data to a server we use a REST API. We are setting up an URI to ScadaAPI and we set up data in URL. This is done by a GET method which is very easy to use. But for more complex queries like for example saving alphanumeric JSON value to a Aplhanumeric data point there is a problem. We are not able to post every data. For example http links are not allowed to be posted. So if we had somewhere saved URL in our config there will be an issue with saving this data to datasource

So...

There should be a mechanism to load data from POST request to save any data to 'string' data point.

**Comment by grzesiekb** [comment]
It is not true! You may can't sent POST.
