### ISSUE TITLE
Create documentation for installing ScadaLTS with a docker on linux

### ISSUE THREAD

**Issue by grzesiekb** [SCADA-LTS/Scada-LTS#363]

**Comment by grzesiekb** [comment]
[Install Scada-LTS on linux](https://github.com/SCADA-LTS/Scada-LTS/wiki/Install-Scada-LTS-on-linux)

**Comment by matiasbarone** [comment]
Is possible to install Scada-LTS on linux with docker??
I cant download Docker Toolbox from: https://kitematic.com/
It's for Mac and Windows.

> [Install Scada-LTS on linux](https://github.com/SCADA-LTS/Scada-LTS/wiki/Install-Scada-LTS-on-linux)
This install is not using docker.
