### ISSUE TITLE
Prepare development environment for Scada-LTS with Intellij IDE

### ISSUE THREAD

**Issue by ArkadiuszParafiniuk** [SCADA-LTS/Scada-LTS#370]

**Comment by grzesiekb** [comment]
1. Import project from eclipse.
2. Set library  - Settings - Path Variables. (add catalina library, add scada).
3. Config tomcat (context.xml, $CATALINA_HOME, tomcat-users.xml.
4. copyToDeploy - (run task),
5. Run tomcat with option jpda "catalina.bat jpda start" 
6. Add configuration (Run/Debug Configuration) Remote.
