### ISSUE TITLE
Moving data to historical database.

### ISSUE THREAD

**Issue by ArkadiuszParafiniuk** [SCADA-LTS/Scada-LTS#371]

**Comment by grzesiekb** [comment]
https://www.ibm.com/support/knowledgecenter/SSKPRS/com.ibm.help.pem.sponsor.tasks.doc/c_purge_archive_overview.html

**Comment by grzesiekb** [comment]
https://dev.mysql.com/doc/mysql-monitor/3.4/en/mem-ui-settings-data-purge-ref.html
