### ISSUE TITLE
Getting Wierd Error

### ISSUE THREAD

**Issue by abhishekricky** [SCADA-LTS/Scada-LTS#423]
WARN  2017-11-21 01:42:38,568 (com.serotonin.mango.rt.dataSource.PollingDataSource.scheduleTimeout:63) - Panel 3A: poll at 2017/11/21 01:42:38 aborted because a previous poll started at 2017/11/21 01:42:08 is still running 

What can be the issue ?

**Comment by grzesiekb** [comment]
We need access to the installation to diagnose it.

**Comment by andrebarradas** [comment]
Hi guys, i have the same problem, any suggestion?

`WARN  2022-05-09 16:37:41,296 (com.serotonin.mango.rt.dataSource.PollingDataSource.scheduleTimeout:63) - GATEWAY: poll at 2022/05/09 16:37:41 aborted because a previous poll started at 2022/05/09 16:36:03 is still running `

**Comment by Limraj** [comment]
Hi @abhishekricky, @andrebarradas, @grzesiekb,

The reason for this message is related to Polling Data Source, i.e. Data Sources that have the update parameter. Now if the current update (calling the scheduleTimeout method and then doPoll) does not execute before the next update, this thread is stopped, with this message. This means that if the update execution time is longer than the period set in the Data Source, it will be updated as often as physically possible. This appears to be correct behavior. 

Regards,
Kamil Jarmusik
