### ISSUE TITLE
Unable to display the text output of point Meta data source type "alphanumeric"

### ISSUE THREAD

**Issue by TomyZacharia** [SCADA-LTS/Scada-LTS#459]
We have started using scadalts recently. We have used scadabr in the past and the problem did not exist.

The following problem is observed.
1. Input point defined as Modbus IP - Data is read as "Coil Status" and binary.  It is available and displaying in watch list as well as Graphical Views
2. This point is used as input to Meta Data source. The point is defined as AlphaNumeric and script has been written to interpret the status and display as either "OFFLINE" or "ONLINE"
3. The output of metadata script is evaluated correctly and is displayed by "Validate Script" button.
4. It is displayed incorrectly in watch list as "(n/a)" and in the graphical view as "null".

We are using ubuntu 16.04, Tomcat 7, mysql 5.7 and openjdk 1.8.

**Comment by grzesiekb** [comment]
I need detailed information that allows me to replicate the indicated situation - For example - script described in the second point.

**Comment by TomyZacharia** [comment]
I am attaching screen shots for each point.
1. screen shot for input data
2. screen shot for the script
3. screen shot of watchlist
4. screen shot of graphical view
![1](https://user-images.githubusercontent.com/35994183/35672085-6a97a96e-0763-11e8-8fde-ab4e94a93925.jpg)
![2](https://user-images.githubusercontent.com/35994183/35672086-6ad9b61a-0763-11e8-9338-844fca23201b.jpg)
![3](https://user-images.githubusercontent.com/35994183/35672087-6b1e0b4e-0763-11e8-94c0-c50054a1478e.jpg)
![4](https://user-images.githubusercontent.com/35994183/35672088-6b645392-0763-11e8-8201-fa5760f55783.jpg)

**Comment by grzesiekb** [comment]
Thank you, I will check it today :) - 
If the modbus value changes, then the value in meta data source will be calculated (in this case). 
It may not necessarily be the reason, I will check it later.

**Comment by grzesiekb** [comment]
### (EN) Unable to display (alphanumeric) the text output of server side script.
#### Thank you for your application and valuable comments.

The above method for calculating the value and its checking is not very optimal.

I suggest you configure the program a little differently.

Namely, the point type set as in Meta data source as:
**Multistate**

![screenshot from 2018-02-02 13-42-43](https://user-images.githubusercontent.com/1280575/35735837-59e64756-0826-11e8-99cd-0bcace4f3d31.png)

Then change the way text is rendered

![screenshot from 2018-02-02 13-43-54](https://user-images.githubusercontent.com/1280575/35735881-7670d936-0826-11e8-8aa8-5d54f123228c.png)

What will work properly.

![screenshot from 2018-02-02 13-44-09](https://user-images.githubusercontent.com/1280575/35735890-7db8bb8c-0826-11e8-8f3d-dcb2418170f0.png)

![screenshot from 2018-02-02 13-48-09](https://user-images.githubusercontent.com/1280575/35735895-8367d540-0826-11e8-8b74-df92a0ca8245.png)

Thank you.

**Comment by TomyZacharia** [comment]
We were able to implement the same successfully. We have used graphic element type "simple point" for implementing the same. Thanks for the reply.

We further need the process for changing the formatting of graphic element "simple point". A button is available with the label "style attribute". Screen shot is attached. We require the settings for changing font size, bold/italic font type, change text box boundary color etc.

![5](https://user-images.githubusercontent.com/35994183/36058795-004a6404-0e50-11e8-8adc-ca5115792c74.jpg)

**Comment by radek2s** [comment]
Alphanumeric data type has been fixed. Now it can display a message with a custom return value from users custom script. It works also in WatchList and View menu. 

Due to styling the "simple point" element here are some examples how it works.
![scada01](https://user-images.githubusercontent.com/22638815/36095212-8daaf8ac-0ff1-11e8-9015-9ebe837c6cd5.JPG)
