### ISSUE TITLE
Docker support for arm (Rasp3)

### ISSUE THREAD

**Issue by JoaoCampos89** [SCADA-LTS/Scada-LTS#460]
There are plans to support arm platform in order to work with raspberry 3?

**Comment by grzesiekb** [comment]
### Not now - but I will try to describe how I prepared the version installed on the Rassbera PI clone
### Unfortunately, it does not work stably on such a computer.

I invite you to follow my blog where, among other things, I describe Scade-LTS https://steemit.com/@grzesiekb

**Comment by Limraj** [comment]
MySQL server no support for the arm/v7 architecture.
This architecture is also 32 bit.
