### ISSUE TITLE
Support for Mqtt?

### ISSUE THREAD

**Issue by JoaoCampos89** [SCADA-LTS/Scada-LTS#461]
Any plans in support Mqtt on Scada-LTS as DataSource? This protocol is used in internet of things platforms. If not there is any tutorial I can read which help add this datasource?

**Comment by grzesiekb** [comment]
## Yes, we plan to separate the data-sourcy
### so that it can be easily expanded (Among other things, about MQTT). 
I would like it to be the next topic on rights, but it does not depend only on me.

**Comment by SoftQ** [comment]
MQTT support in ScadaLTS may be achieved  using RabbitMQ plugin and Scada-LTS AMQP datasource that would be receiving/publishing to RabbitMQ.
