### ISSUE TITLE
HTTP Receiver Data Source 

### ISSUE THREAD

**Issue by abhishekricky** [SCADA-LTS/Scada-LTS#472]
After 0.0.9.1 Update, Alphanumeric values are being stored properly in HTTP Receiver Data Source 

But using timestamp tag like & __time is not working

**Comment by grzesiekb** [comment]
What you mean by (like & __time is not working)? Thank you in advance for you help.

**Comment by justindressler** [comment]
Hi I was able to replicate this issue the __time parameter does not override the time the change is recorded.
So if I POST or GET the httpds end point it records the data point value at the time received not the time provided by the __time parameter.

**Comment by justindressler** [comment]
This also effects other data sources at least DNP. Events should be recorded with the timestamp from the source is specified.

**Comment by waqassiddiqi** [comment]
I tested it on latest version (`/new/develop`) and it seems to be working.
