### ISSUE TITLE
Add possiblity to import new graphics for graphical components in the runtime(without server restarting)

### ISSUE THREAD

**Issue by ArkadiuszParafiniuk** [SCADA-LTS/Scada-LTS#485]

**Comment by grzesiekb** [comment]
1. The attempt to load images into the assets directory
2. The assets directory does not require a restart to update content in the form of links, for example <img src = "./ assets / 1.jpg" />
3. Checking how to set a picture in the form of a link for graphical components.

Graphical components:

![screenshot from 2018-03-09 10-59-41_1](https://user-images.githubusercontent.com/1280575/37201867-2e4d4774-2389-11e8-9448-7441f5939db7.png)

**Comment by grzesiekb** [comment]
Resolved in [509](https://github.com/SCADA-LTS/Scada-LTS/issues/509)
