### ISSUE TITLE
Change view "Graphical views" error page

### ISSUE THREAD

**Issue by mario1mario** [SCADA-LTS/Scada-LTS#625]
Testing e.g. Test case TC229 "System exception" error test:  After the error message appears (3rd point of the case), there are no Polish characters on the menu

**Comment by grzesiekb** [comment]
Please send a picture (print screen)

**Comment by mario1mario** [comment]
The screen to the comment above
![obraz](https://user-images.githubusercontent.com/38043286/41664567-4acc57a0-74a6-11e8-81ff-4c346c7a10fe.png)
