### ISSUE TITLE
Update docker link on main readme.

### ISSUE THREAD

**Issue by markrey** [SCADA-LTS/Scada-LTS#681]
The current readme has:
https://github.com/SCADA-LTS/Scada-LTS#to-run-scadalts-on-docker
`docker pull dockergb/scadalts-dev` as a master link 

but as a part of Travis - link is 
`https://hub.docker.com/r/scadalts/scadalts/`

Can someone update the documentation? I would like to check and provide pull request for docker performance improvements - i have updated in my own fork already.

**Comment by SoftQ** [comment]
Thank You for Your feedback!
We are in process of migrating to scadalts/scadalts "official" Docker.  Docs shall be corrected soon.  With regard to Docker performance improvements,  do You mean switching to Quay.io? Please contact us to email to info@Scada-LTS.org as we would  like to discuss other  Docker-related changes.
