### ISSUE TITLE
Rest API Documentation

### ISSUE THREAD

**Issue by JoaoCampos89** [SCADA-LTS/Scada-LTS#691]
There is plans to document the java rest api? Here [https://swagger.io/tools/swagger-ui/](swagger), it is an example of  documentation. The documentation helps developers create mobile apps for Scada-LTS.

**Comment by grzesiekb** [comment]
It is the most important thing to do.

**Comment by grzesiekb** [comment]
Not only for the mobile application but also dedicated Graphical View which can be based on the REST API
