### ISSUE TITLE
Data lost after restart container 

### ISSUE THREAD

**Issue by pablorq** [SCADA-LTS/Scada-LTS#737]
Hi all,

Using the following command, every time the container is started all data and configuration is lost.

docker run -it -e DOCKER_HOST_IP=`docker-machine ip` -p 81:8080 scadalts/scadalts /root/start.sh

Is there any way to maintain the data after restart the host or the container?

Thank you in advance.

Regards,

**Comment by ArkadiuszParafiniuk** [comment]
When docker container is stopped you must use  `docker start {containerID}` command. `docker run` creates a new docker container. To see list of stopped container use `docker ps -a`.
Regards

**Comment by pablorq** [comment]
Ok. Thank you for the info!
