### ISSUE TITLE
No events or alarms flags shown in develop branch

### ISSUE THREAD

**Issue by danibeni** [SCADA-LTS/Scada-LTS#739]
Working with Scada-LTS develop branch, I have noticed that NO event or alarm flag (Information, Urgent, Critical,...) is shown in the header (upper side) of the Scada-LTS screen. Besides, no event appear in the pending alarms list shown when you clicked the Alarms menu item. I don not know if this is done on purpose, but I would need that access to events and pending alarms for new features developing.

**Comment by danibeni** [comment]
I have seen that the events and alarms are not stored in the events table of the database. After some research, it seems that the default value of ALARM_EXPORT TYPE is set to 0 in SystemSettingsDAO.java, but in EventManager.java class the event is only stored if SystemSettingsDAO.ALARM_EXPORT_TYPE is equal to the constant value EventExporter.DEFAULT, and this value is 1, so the raised events are never stored in the database and, therefore, no events are shown in the header of SCADA-LTS screen or in the Alarms menu item.

I have checked that changing the ALARM_EXPORT_TYPE default value in SystemSettingsDAO.java class to 1, allows the events to be stored in the database and are shown in the SCADA-LTS screen.

Is it this the expected behavior of develop branch or is it a bug?

**Comment by SoftQ** [comment]
Thank You for Your help and diagnosis! We were aware events are affected after merging Radek's work to development - he did a tricky error while implementing functionality of AMQP event exporting to RabbitMQ .  Arek will correct this issue.
