### ISSUE TITLE
Docker versions/tags

### ISSUE THREAD

**Issue by pablorq** [SCADA-LTS/Scada-LTS#749]
Hi,

I'm having problems with the 'latest' docker image (updated 6 days ago) and I'm trying to get the previous version, but in the docker store there's only 'latest' and 'develop'.

Can you, please, upload to docker store the previous versions with a version tag?

Now I've a non working docker image and no previous one.  :(

Regards.

**Comment by grzesiekb** [comment]
It doesn't work perfectly yet but we have a docker lates scadalts/scadalts and a docker with current work scadalts/scadalts:new_development and in a moment will be scadalts/scadalts: s_development.
