### ISSUE TITLE
Displaying the last and adding a new users note about the data point on the views screen.

### ISSUE THREAD

**Issue by ArkadiuszParafiniuk** [SCADA-LTS/Scada-LTS#762]
- displaying the most last added users note next to the basic information about data point when hovering over the point on the page of graphic views

- together with the note should be displayed the date of its addition and the name of the user who created it

- regardless of whether a note already exists or not after hovering over a point, there should be a button that allows you to add a new note

- the implementation will be an extension of the current "user notes" functionality

**Comment by grzesiekb** [comment]
Requires testing and in my opinion a different approach to solve the problem (without using jsp). So we render the data unnecessarily every time we enter the view instead of when the user asks for it. The second question is how to hide data that we have already downloaded without paging.
