### ISSUE TITLE
Add possibility to lock changing data point value by user

### ISSUE THREAD

**Issue by ArkadiuszParafiniuk** [SCADA-LTS/Scada-LTS#763]
- the user can lock the change of this point by himself and other users, as well as unlock it if it is locked

- to be able to lock/unlock the point, the user must have the "set" permission to the data point

- to lock or unlock the change of point values ​, user must leave a note that will inform other users about reasons for locking/unlocking the point

- locking/unlocking the data point should be possible on the screens "data point details", "views", "watchlists".

- locking or unlocking a point creates an event whose login level will be possible to be set in "system settings" and contains message witch reason of action

- when the point is locked, a padlock appears in the setting field of the point value instead of the "set" button

- when the user clicks on the padlock he/she will be informed that the point is locked and he/she will get the suggestion that can remove the blockade

- creating a note while locking/unlocking a data point is obligatory, and the minimum length of the note is 2 characters

- as part of the implementation, a new "user locks" table will be created

- the implementation will enable its later extension to block eg. reports, views, etc.

**Comment by grzesiekb** [comment]
I think it is a very useful function and written in a clear way but requires testing. And this is part of the permissions that suggests that some users have access to read level points. And a point locking in my opinion has a slightly different meaning.
