### ISSUE TITLE
Problem with Event handlers

### ISSUE THREAD

**Issue by grzesiekb** [SCADA-LTS/Scada-LTS#771]
branch:develop

I can't create "Event detectors".
eg:
1. Create
![event_detectors](https://user-images.githubusercontent.com/1280575/50774189-1860cb80-1293-11e9-8c7c-cf223ae57702.png)

2. Save
![event_detectors_save](https://user-images.githubusercontent.com/1280575/50774276-4cd48780-1293-11e9-9b32-89ac3c213fea.png)

3. Lost "Event detector".
![lost_event_detector](https://user-images.githubusercontent.com/1280575/50774360-7f7e8000-1293-11e9-88b0-591fe2956726.png)

**Comment by SoftQ** [comment]
It seems it is not possible to add event detector to datapoint.

**Comment by mateuszhyski** [comment]
This one issue is solved in branche 

feature/#802_Event_Detector_fix_operationUpdate_on_develop
