### ISSUE TITLE
Event detectors fix on develop

### ISSUE THREAD

**Issue by grzesiekb** [SCADA-LTS/Scada-LTS#786]
In pull-request analyze (https://github.com/SCADA-LTS/Scada-LTS/pull/787/files) changes:

1. dataPointDetails.jsp
2. dataSourceEdit.jsp
3. editAmqp.jsp
4. customEditor.jsp
5. graphicRendererEditor.jsp
6. staticEditor.jsp
7. login.jsp
8. systemSettings.jsp
9. users.jsp
10. viewEdit.jsp
11. alarmList.jsp
12. infoContent.jsp
13. comments.tag
14. lastComment.tag
15. UsersProfileDao.java
16. DSCommandsScriptContextObject.java
**17. AlarmListComponent.java**  
18. ContextualizedScriptVO.java
19. Common.java
20. MangoContextListener.java
21. ScriptSessionAndUsers.java
22. EventManager.java
23. BinaryValue.java
24. ModbusSerialDataSource.java
25. DataPurge.java
26. DataSourceVO.java
27. Permissions.java
28. DataSourceEditDwr.java
**29. EmportDwr.java** 
30. SystemSettingsDwr.java
31. UsersDwr.java
32. ViewDwr.java
33. DataPointUserDAO.java
34. SystemSettingsDAO.java
35. PointHierarchyDAO.java
36. PointHierarchyXidDAO.java
37. UserService.java
38. WatchListService.java
39. DataPointAPI.java
40. ViewAPI.java
41. WatchListAPI.java
42. ViewEditContorller.java
43. ViewEditForm.java
44. AmqpDataSourceRT.java
45. AmqpDataSourceVO.java
46. AmqpPointLocatorRT.java
47. AmqpPointLocatorVO.java
48. EventExporter.java
49. RabbitMqExporter.java

Because js codes are not separated can affect the code in others site.
Similarly, java code is not divided into modules, and can have an impact but smaller because it is hidden in classes.

Therefore, you should check the changes in all the indicated files.

Suggestion for the names of packages containing tests.
In my opinion, it should be similar to:
  1. /src/test/...  src.test  
  2. /java/src/test/...  src.test

**Comment by mateuszhyski** [comment]
I am closing this issue because of solution is on branche 802_Event_Detector_fix_operationUpdate_on_develop
