### ISSUE TITLE
Unable to disable System event alarm User Login

### ISSUE THREAD

**Issue by OlleRatu** [SCADA-LTS/Scada-LTS#806]
When logging in with to the REST-service I always get an entry in the alarm log even if it is set to None in System event alarm settings. It floods the alarm list making it useless.

**Comment by OlleRatu** [comment]
Seems to be all events with Alarm Level "None".

**Comment by grzesiekb** [comment]
Also, "None" alarms should not be written to the database.
And I would like it to be at the alarm to specify the path calling REST API (when the alarm occurs calls REST API)

**Comment by SoftQ** [comment]
Thank You, we will take care of Your request very soon
