### ISSUE TITLE
Event Handlers message errors and duplicate handlers

### ISSUE THREAD

**Issue by hilariodaufemback** [SCADA-LTS/Scada-LTS#822]
I created two event detectors, testing the battery voltage. When lowering by 12 V creates a yellow alert and when less than 11.5 V red alert.
When I go into Event Handlers to send an email as soon as the event is detected and I click on the event, for example, alert yellow, it shows me the following message: "Empty String". Even giving the OKs, it allows the creation of the Event Handler. When you save it it issues the following message: "A server error has occurred. More information may be available in the console." I consulted the catalina.out, until I found where it shows the record of the error, but without great explanations. After saving the event handler, it repeats the same event for the other event detectors of the same point. If you create a new handler for another detector at the same point, it repeats the same for the other points.

**Comment by grzesiekb** [comment]
I think that despite some problems, this function it's working correctly.
