### ISSUE TITLE
Server overload when accessing graphical view.

### ISSUE THREAD

**Issue by OlleRatu** [SCADA-LTS/Scada-LTS#834]
When opening a graphical view with one "Enhanced image chart" with 3 values 5 min sample time  over a period of one month CPU load goes to 100%.
MySQL 75%, Java 25%.
Something need to be fixed to make it usable :-)

**Comment by OlleRatu** [comment]
My impression is that i continuously reads all data present from the database in the chart.

**Comment by grzesiekb** [comment]
It probably is as you write that it reads all the data whenever.

**Comment by grzesiekb** [comment]
It needs remote installation access to diagnose the problem.
