### ISSUE TITLE
Language switch to Chinese, the page appears unreadable code

### ISSUE THREAD

**Issue by iotclouddeveloper** [SCADA-LTS/Scada-LTS#835]
Hello,
I'm going to run the scadabr.war (v.0.0.9.8),After I login in, I switch the language to Chinese, the page appears unreadable code.
where is the problem???
thanks.

**Comment by grzesiekb** [comment]
I do not have that effect.
Do you use the scada version on the [docker](https://hub.docker.com/r/scadalts/scadalts)?

**Comment by iotclouddeveloper** [comment]
![image](https://user-images.githubusercontent.com/34469153/58600780-85174980-82b8-11e9-8251-0090ae66d084.png)
I donot use the scada version on the docker ,I deploy v.0.0.9.8 on the tomcat.
I found  that there are less items in messages_zh.properties than in messages_en.properties. Is that the reason?

**Comment by liaoah** [comment]
@grzesiekb 
the docker also have the same problem

**Comment by grzesiekb** [comment]
@liaoah Please print screen from docker.

**Comment by Limraj** [comment]
Hi @iotclouddeveloper and @liaoah,
We fixed it in this issue: https://github.com/SCADA-LTS/Scada-LTS/issues/2421

The problem with encoding and setting the language for the user should not occur from version 2.7.5.3, (2.7.4.1 fixed encoding, and 2.7.5.3 added ability save lang per user)

Regards,
Kamil Jarmusik
