### ISSUE TITLE
Contribute

### ISSUE THREAD

**Issue by phbs82** [SCADA-LTS/Scada-LTS#840]
The Readme file is in process of making. Openthe code for contribute. 
There is a lot of projects,protocols and functionalities that can be add to the projet.

**Comment by phbs82** [comment]
I want to conrtribute. Would be perfect if we had an tutorial to import project on eclipse to make changes.

**Comment by grzesiekb** [comment]
I do not know if this is up to date but the descriptions are on the wiki:
[Eclipse](https://github.com/SCADA-LTS/Scada-LTS/wiki/Prepare-environment-to-develop-(Eclipse-J2E-IDE))
[IneliJ](https://github.com/SCADA-LTS/Scada-LTS/wiki/Prepare-environment-to-develop-(IntelliJ-Community))
