### ISSUE TITLE
repairing the docker

### ISSUE THREAD

**Issue by grzesiekb** [SCADA-LTS/Scada-LTS#940]

**Comment by pablorq** [comment]
Hi,

This change is already updated on docker?

The docker image available today is from 04/06/19.

Regards.

**Comment by grzesiekb** [comment]
@pablorq  this is for checking
(21 days ago marge to new/develop) create docker:new_develop (tag: new_develop)
but last change docker:new_develop is 20 days ago 
![Screenshot from 2019-08-05 14-36-01](https://user-images.githubusercontent.com/1280575/62465140-82d8dc00-b78e-11e9-9a7e-ced6df7a8b2c.png)

**Comment by pablorq** [comment]
Sorry for the late response.

As you show in the picture, the changes are on the 'new_develop' branch and no in the 'latest'.

My question was about to provide the changes on the latest docker release.

Thank you anyway!

**Comment by grzesiekb** [comment]
Please use the scadals/scadalts:siv_dev.
I will try to make sure that after installation on the production of the last version, it will be released on docker scadalts/scadalts:latest

**Comment by pablorq** [comment]
Ok. I will try it in the future.

Thank you!
