### ISSUE TITLE
Bad special characters 

### ISSUE THREAD

**Issue by jeffersonpimenta** [SCADA-LTS/Scada-LTS#949]
After install and switch to portuguese language, i got bad characters, example:

UsuÃ¡rio   instead of Usuário
AtÃ©       instead of Até
GrÃ¡fico   instead of Gráfico
prÃ³prio  instead of próprio
ExceÃ§Ã£o  instead of Exceção
PerÃ­odo     instead of período
atualizaÃ§Ã£o   instead of atualização

and so on...

Side question: how i do to help the project? Like translations to PT-BR?

**Comment by jeffersonpimenta** [comment]
Partial solution:

Update /var/lib/tomcat7/conf/*.xml  to utf-8

But i still have "Informa��o" on the top center.

**Comment by grzesiekb** [comment]
@jeffersonpimenta  It works correctly on the docker

![Screenshot from 2019-08-07 11-57-37](https://user-images.githubusercontent.com/1280575/62614055-f69ff380-b90a-11e9-9f64-a1cc76044c00.png)

**Comment by jeffersonpimenta** [comment]
How can i contribute for translations and corrections?

Example: in modbus serial datasource i have "Quantizção" instead of "Quantização", missing a "a" letter

**Comment by jeffersonpimenta** [comment]
On graphical views, enhanced image chart, i got this

![image](https://user-images.githubusercontent.com/11169349/62654025-514e4500-b935-11e9-8399-14e1243a30c4.png)

**Comment by Limraj** [comment]
Discussion: https://github.com/SCADA-LTS/Scada-LTS/discussions/2420 (issue #2421 and #2370)
Is corrected from [2.7.4.1](https://github.com/SCADA-LTS/Scada-LTS/releases/tag/v2.7.4.1) Scada-LTS
