### ISSUE TITLE
Add missing AMQP datasource

### ISSUE THREAD

**Issue by radek2s** [SCADA-LTS/Scada-LTS#966]
On September 24 last year to this repository has been merged a new AMQP datadource for ScadaLTS. Due some other issues was created a new development branch which not included this DS. 
## Tasks:
-  Merge AMQP code to new develop

**Comment by liaoah** [comment]
look forward to

**Comment by minghu** [comment]
@liaoah what is your company?you want  do a pump or  equipment  Remote management  solutions?

**Comment by liaoah** [comment]
@minghu , i am a freelance, work at home.

**Comment by jeffersonpimenta** [comment]
Any news about the AMQP or mqtt support?
