### ISSUE TITLE
the page's footer in some page show in not right place

### ISSUE THREAD

**Issue by liaoah** [SCADA-LTS/Scada-LTS#976]
<div class="footer" style="width:100%; text-align:center; ">
    <span>&copy;2012-2018  <fmt:message key="footer.rightsReserved"/></span>
</div>

![image](https://user-images.githubusercontent.com/29118081/64025103-8d5c7a80-cb6e-11e9-9601-19f3f5eb3ef2.png)

**Comment by liaoah** [comment]
<div class="footer" style="width:100%; text-align:center; **position: fixed; bottom: 10px;**">

**Comment by liaoah** [comment]
<div class="footer" style="width:100%; text-align:center; position: fixed; bottom: 10px;">

**Comment by liaoah** [comment]
div class="footer" style="width:100%; text-align:center; **position: fixed; bottom: 10px;"**

**Comment by fabiodurao** [comment]
Page misconfiguration errors usually happen when we add html components to the page, open a tag, and don't close:

eg.:
"<a href=www.scadabr.org.br> <img src = logo_sbr.png>"

not putting "</a>" gives this kind of problem, or it can make half the page a link hehe.

If the component is missing, edit the page, and click minimize components, they will appear small (like a lego) and you will be able to find something lost.
