### ISSUE TITLE
Docker image does not allow login to Tomcat

### ISSUE THREAD

**Issue by DrWhoDrWho** [SCADA-LTS/Scada-LTS#988]
Runinng Docker image scadalts/scadalts starts Tomcat. There are some errors about security and no default directory.
Pressing button on Tomcat webpage results in a challange for a username/password, but the default admin/admin does not work.

Running Docker image scadalts/scadalts:new_develop starts Tomcat with fewer errors but throws a Java exception. 
Pressing button on Tomcat webpage results in a challange for a username/password, but the default admin/admin still does not work.

Docker images
REPOSITORY          TAG                 IMAGE ID            CREATED
scadalts/scadalts   new_develop         63b2667a3c5b        12 hours ago
scadalts/scadalts   latest              4a8578395dbe        3 months ago

Environment
Docker 19.03.1 built 2019-07-25
Microsoft Windows 10 Enterprise Version 1809 build 17763.678
HyperV running

**Comment by Limraj** [comment]
Hi @DrWhoDrWho,

A lot has changed since then, if you can check the current versions of the app and the [docker-compose.yml](https://github.com/SCADA-LTS/Scada-LTS/blob/develop/docker-compose.yml) file.

Regards,
Kamil Jarmusik
